### ISSUE TITLE
Install error when library is in requirements.txt: No module named 'torch'

### ISSUE THREAD

**Issue by alexanderb14** [rusty1s/pytorch_scatter#145]
Hi,

your pytorch_geometric and associated libraries are great work! Thanks for providing this.

However, currently I am facing a problem when automating the install process of my project. My requirements.txt file contains among others:

```
torch
torch-scatter
```

When installing the requirements, I am getting:

```
Collecting torch
  Using cached torch-1.5.1-cp38-cp38-manylinux1_x86_64.whl (753.2 MB)
Collecting torch-scatter
  Using cached torch_scatter-2.0.5.tar.gz (20 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mmf5_au2/torch-scatter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mmf5_au2/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-mmf5_au2/torch-scatter/pip-egg-info
         cwd: /tmp/pip-install-mmf5_au2/torch-scatter/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mmf5_au2/torch-scatter/setup.py", line 6, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

This is because torch is imported in the setup.py of torch-scatter and not available yet in this pip install process I assume.
What is the preferred way to include pytorch_geometric in my requirements?

Thanks,
Alex

**Comment by rusty1s** [comment]
Yes, that's a current limitation. You can get around it by installing the extensions from wheels, or outsourcing the `torch` requirement.
