### ISSUE TITLE
Can't install from requirements.txt

### ISSUE THREAD

**Issue by kwohlfahrt** [rusty1s/pytorch_scatter#17]
I can't install this package from a `requirements.txt` containing this package and `torch`. I think this is because `torch` should be listed in `setup_requires`? If that is the case, `pytorch_sparse` has the same issue. The error is the following:

```
Collecting torch==0.4.1 (from -r requirements.txt (line 29))
  Downloading https://files.pythonhosted.org/packages/49/0e/e382bcf1a6ae8225f50b99cc26effa2d4cc6d66975ccf3fa9590efcbedce/torch-0.4.1-cp36-cp36m-manylinux1_x86_64.whl (519.5MB)
Collecting torch-scatter@ git+https://github.com/rusty1s/pytorch_scatter.git@216b03cda7157439278a1e20983dcc32b5e9d398#egg=pytorch_scatter from git+https://github.com/rusty1s/pytorch_scatter.git@216b03cda7157439278a1e20983dcc32b5e9d398#egg=pytorch_scatter (from -r requirements.txt (line 30))
  Cloning https://github.com/rusty1s/pytorch_scatter.git (to revision 216b03cda7157439278a1e20983dcc32b5e9d398) to /tmp/pip-install-7865i18f/torch-scatter
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7865i18f/torch-scatter/setup.py", line 2, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
```

**Comment by rusty1s** [comment]
Hi, we can't list `torch` as a requirement, because it is already needed for the installation process. You need to install torch first, so a workaround could be to create two `requirements.txt` files.

**Comment by kwohlfahrt** [comment]
Thanks for the quick response. After some reading it seems that `setup_requires` is not recommended anymore, so that's a good workaround. If I come up with anything nicer I'll open a PR.
