### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda'

### ISSUE THREAD

**Issue by GeniusYx** [rusty1s/pytorch_scatter#170]
Dear：
I installed the packages as follows in linux：
`
pytorch                   1.0.1
torch-cluster             1.2.4              
torch-geometric           1.0.3
torch-scatter             1.1.2 
torch-sparse              0.2.4
torch-spline-conv         1.0.6
`
I used 
`
pip install torch-scatter==1.1.2 
`
to install the torch-scatter. But something wrong happened as follows:
`
Python 3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.>>> import torch
>>> import torch_scatter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jjpeng/.conda/envs/yxwang_pre1/lib/python3.7/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home/jjpeng/.conda/envs/yxwang_pre1/lib/python3.7/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home/jjpeng/.conda/envs/yxwang_pre1/lib/python3.7/site-packages/torch_scatter/utils/ext.py", line 5, in <module>
    import torch_scatter.scatter_cuda
ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda'
>>> 
`

Here is my log(when i run pip install torch-scatter==1.1.2 )
`2020-10-28T16:15:13,134 Using pip 20.2.4 from /home/jjpeng/.conda/envs/yxwang_pre1/lib/python3.7/site-packages/pip (python 3.7)
2020-10-28T16:15:13,134 Non-user install because site-packages writeable
2020-10-28T16:15:13,194 Created temporary directory: /tmp/pip-ephem-wheel-cache-e9d1hi5s
2020-10-28T16:15:13,194 Created temporary directory: /tmp/pip-req-tracker-4vh6j2i4
2020-10-28T16:15:13,194 Initialized build tracking at /tmp/pip-req-tracker-4vh6j2i4
2020-10-28T16:15:13,194 Created build tracker: /tmp/pip-req-tracker-4vh6j2i4
2020-10-28T16:15:13,194 Entered build tracker: /tmp/pip-req-tracker-4vh6j2i4
2020-10-28T16:15:13,194 Created temporary directory: /tmp/pip-install-2gctss08
2020-10-28T16:15:13,195 Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
2020-10-28T16:15:13,201 1 location(s) to search for versions of torch-scatter:
2020-10-28T16:15:13,201 * https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/
2020-10-28T16:15:13,201 Fetching project page and analyzing links: https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/
2020-10-28T16:15:13,201 Getting page https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/
2020-10-28T16:15:13,202 Found index url https://pypi.tuna.tsinghua.edu.cn/simple
2020-10-28T16:15:13,378   Found link https://pypi.tuna.tsinghua.edu.cn/packages/29/96/566ac314e796d4b07209a3b88cc7a8d2e8582d55819e33f72e6c0e8d8216/torch_scatter-0.3.0.tar.gz#sha256=9e5e5a6efa4ef45f584e8611f83690d799370dd122b862646751ae112b685b50 (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 0.3.0
2020-10-28T16:15:13,378   Found link https://pypi.tuna.tsinghua.edu.cn/packages/6a/b0/ecffacddf573c147c70c6e43ce05d24f007155ce3fb436959d3d2a24da46/torch_scatter-1.0.2.tar.gz#sha256=ccda794c25265b3450206b7fb0bf74f16a0b45f3f72d9547a42e44648a32faee (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.0.2
2020-10-28T16:15:13,379   Found link https://pypi.tuna.tsinghua.edu.cn/packages/08/09/07b106f3e74246f4ecf6517013a053b6dd7486c4f889d81f39adc662431f/torch_scatter-1.0.3.tar.gz#sha256=e626993194819ba65cdf89a52fbbb7780569d9e157bc63dbef13ead6b7a33930 (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.0.3
2020-10-28T16:15:13,379   Found link https://pypi.tuna.tsinghua.edu.cn/packages/2d/70/df2bc259d9606f00854ca43b6839f9047ec44900563435e0067584c93864/torch_scatter-1.0.4.tar.gz#sha256=ec004d687e47da9d5477407849d815629fc8b571ee87aeeebf6af8ed6f16defc (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.0.4
2020-10-28T16:15:13,379   Found link https://pypi.tuna.tsinghua.edu.cn/packages/2f/97/c50a6aeaedc6924180c6f5810d2a7405ce11aa9b82ba4284badad549d665/torch_scatter-1.1.0.tar.gz#sha256=e534cc2ecb2f9d9b559b1513cd411737d26ea5585d1d65ff571fec55f42a49de (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.1.0
2020-10-28T16:15:13,379   Found link https://pypi.tuna.tsinghua.edu.cn/packages/91/5f/eb1d3ef3810cb1165859d40db4d9ee6d7f1dfef97d7e5c34010055f43d95/torch_scatter-1.1.1.tar.gz#sha256=9db7f2c0a5cddf6cfde633e33db7c2c94eaab163e9f8edb46460d6414cc97917 (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.1.1
2020-10-28T16:15:13,379   Found link https://pypi.tuna.tsinghua.edu.cn/packages/d4/83/67eeea00c2db1959e2ff95d8680dbd756977bfab254bda8658f09dc3bc11/torch_scatter-1.1.2.tar.gz#sha256=766c2476f5da5ffc25fa8e249ccf50f594031cdce3922abb23559e8e3b14337a (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.1.2
2020-10-28T16:15:13,379   Found link https://pypi.tuna.tsinghua.edu.cn/packages/07/c0/f7ac424496f4a3bcb31aa993fba29077a6d42fc2624c66e90b58a566a98e/torch_scatter-1.2.0.tar.gz#sha256=3a0259105d07d264c740eec8e4267260a5c144cf55472abd26022fff4fd73281 (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.2.0
2020-10-28T16:15:13,379   Found link https://pypi.tuna.tsinghua.edu.cn/packages/24/b7/680c3b392a4b55a0ebfb480aabb0d5c188e94bb21790104175c8cd614947/torch_scatter-1.3.0.tar.gz#sha256=bf7d561b8ef12b39a99f5797c90b989a0ce2c3ee4de74dff3b170f2d8566e1d4 (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.3.0
2020-10-28T16:15:13,379   Found link https://pypi.tuna.tsinghua.edu.cn/packages/35/d4/750403a8aa32cdb3d2d05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz#sha256=54cbad248350165ddc921ded3fe7a69be5d30c6536273a1a3282e375289f86ec (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.3.1
2020-10-28T16:15:13,379   Found link https://pypi.tuna.tsinghua.edu.cn/packages/30/d9/1d5fd4d183dabd9e0a1f7008ecf83318432359f4cc27480e3f2212f44d9c/torch_scatter-1.3.2.tar.gz#sha256=890e8f9da2d57431912182960b71bf6c56397de42c2464907a6e9c583164bf06 (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.3.2
2020-10-28T16:15:13,379   Found link https://pypi.tuna.tsinghua.edu.cn/packages/b8/c3/8bad887ffa55c86f120ef5ae252dc0e357b3bd956d9fbf45242bacc46290/torch_scatter-1.4.0.tar.gz#sha256=5999ef256154e5a99445118c1a53f95cf0f95ef7b5cd8d3b256101125479cc2e (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 1.4.0
2020-10-28T16:15:13,379   Found link https://pypi.tuna.tsinghua.edu.cn/packages/28/f7/fa4e61587169924203a32416f7835939fdd79994eaa429b4f8ef8f0e07e2/torch_scatter-2.0.2.tar.gz#sha256=49d3059b7be93d3f2c328fdc6daa3a8479e3dc4a50c8247aef913177122db671 (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/), version: 2.0.2
2020-10-28T16:15:13,379   Found link https://pypi.tuna.tsinghua.edu.cn/packages/36/2a/ef3d841ec577e2231662ef86af983c6c7c7d509a0e1d9f12949d0218b492/torch_scatter-2.0.3.tar.gz#sha256=1c4b9cb0f6a195c20d8c4b6230d086cae6965b7eb08f80bd2ec050a094b8e563 (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/) (requires-python:>=3.6), version: 2.0.3
2020-10-28T16:15:13,379   Found link https://pypi.tuna.tsinghua.edu.cn/packages/98/a9/47cd92673b6ba251240d587815c763baac2099b07bb76fecdb3b7ae5cece/torch_scatter-2.0.4.tar.gz#sha256=db6c9eca919b86f3eb6102dd0e1215af72e39ed3a4e8d142e6a21d3f20d5c244 (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/) (requires-python:>=3.6), version: 2.0.4
2020-10-28T16:15:13,379   Found link https://pypi.tuna.tsinghua.edu.cn/packages/01/45/cd93ed3227248773ba8bc4b3beaa04e8bddb127a793a41bad875369951b3/torch_scatter-2.0.5.tar.gz#sha256=148fbe634fb9e9465dbde2ab337138f63650ed8abbac42bb3f565e3fe92e9b2f (from https://pypi.tuna.tsinghua.edu.cn/simple/torch-scatter/) (requires-python:>=3.6), version: 2.0.5
2020-10-28T16:15:13,380 Given no hashes to check 1 links for project 'torch-scatter': discarding no candidates
2020-10-28T16:15:13,381 Using version 1.1.2 (newest of versions: 1.1.2)
2020-10-28T16:15:13,381 Collecting torch-scatter==1.1.2
2020-10-28T16:15:13,381   Created temporary directory: /tmp/pip-unpack-qx2c2rbb
2020-10-28T16:15:13,424   Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d4/83/67eeea00c2db1959e2ff95d8680dbd756977bfab254bda8658f09dc3bc11/torch_scatter-1.1.2.tar.gz (12 kB)
2020-10-28T16:15:13,428   Added torch-scatter==1.1.2 from https://pypi.tuna.tsinghua.edu.cn/packages/d4/83/67eeea00c2db1959e2ff95d8680dbd756977bfab254bda8658f09dc3bc11/torch_scatter-1.1.2.tar.gz#sha256=766c2476f5da5ffc25fa8e249ccf50f594031cdce3922abb23559e8e3b14337a to build tracker '/tmp/pip-req-tracker-4vh6j2i4'
2020-10-28T16:15:13,428     Running setup.py (path:/tmp/pip-install-2gctss08/torch-scatter/setup.py) egg_info for package torch-scatter
2020-10-28T16:15:13,428     Created temporary directory: /tmp/pip-pip-egg-info-6z4i1hha
2020-10-28T16:15:13,428     Running command python setup.py egg_info
2020-10-28T16:15:17,246     running egg_info
2020-10-28T16:15:17,246     creating /tmp/pip-pip-egg-info-6z4i1hha/torch_scatter.egg-info
2020-10-28T16:15:17,246     writing /tmp/pip-pip-egg-info-6z4i1hha/torch_scatter.egg-info/PKG-INFO
2020-10-28T16:15:17,246     writing dependency_links to /tmp/pip-pip-egg-info-6z4i1hha/torch_scatter.egg-info/dependency_links.txt
2020-10-28T16:15:17,246     writing top-level names to /tmp/pip-pip-egg-info-6z4i1hha/torch_scatter.egg-info/top_level.txt
2020-10-28T16:15:17,247     writing manifest file '/tmp/pip-pip-egg-info-6z4i1hha/torch_scatter.egg-info/SOURCES.txt'
2020-10-28T16:15:17,255     reading manifest file '/tmp/pip-pip-egg-info-6z4i1hha/torch_scatter.egg-info/SOURCES.txt'
2020-10-28T16:15:17,255     reading manifest template 'MANIFEST.in'
2020-10-28T16:15:17,256     writing manifest file '/tmp/pip-pip-egg-info-6z4i1hha/torch_scatter.egg-info/SOURCES.txt'
2020-10-28T16:15:17,309   Source in /tmp/pip-install-2gctss08/torch-scatter has version 1.1.2, which satisfies requirement torch-scatter==1.1.2 from https://pypi.tuna.tsinghua.edu.cn/packages/d4/83/67eeea00c2db1959e2ff95d8680dbd756977bfab254bda8658f09dc3bc11/torch_scatter-1.1.2.tar.gz#sha256=766c2476f5da5ffc25fa8e249ccf50f594031cdce3922abb23559e8e3b14337a
2020-10-28T16:15:17,309   Removed torch-scatter==1.1.2 from https://pypi.tuna.tsinghua.edu.cn/packages/d4/83/67eeea00c2db1959e2ff95d8680dbd756977bfab254bda8658f09dc3bc11/torch_scatter-1.1.2.tar.gz#sha256=766c2476f5da5ffc25fa8e249ccf50f594031cdce3922abb23559e8e3b14337a from build tracker '/tmp/pip-req-tracker-4vh6j2i4'
2020-10-28T16:15:17,315 Building wheels for collected packages: torch-scatter
2020-10-28T16:15:17,316   Created temporary directory: /tmp/pip-wheel-wloa6idz
2020-10-28T16:15:17,316   Destination directory: /tmp/pip-wheel-wloa6idz
2020-10-28T16:15:17,316   Running command /home/jjpeng/.conda/envs/yxwang_pre1/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2gctss08/torch-scatter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2gctss08/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-wloa6idz
2020-10-28T16:15:17,677   running bdist_wheel
2020-10-28T16:15:17,677   running build
2020-10-28T16:15:17,677   running build_py
2020-10-28T16:15:17,684   creating build
2020-10-28T16:15:17,685   creating build/lib.linux-x86_64-3.7
2020-10-28T16:15:17,685   creating build/lib.linux-x86_64-3.7/test
2020-10-28T16:15:17,685   copying test/test_std.py -> build/lib.linux-x86_64-3.7/test
2020-10-28T16:15:17,685   copying test/test_multi_gpu.py -> build/lib.linux-x86_64-3.7/test
2020-10-28T16:15:17,685   copying test/test_forward.py -> build/lib.linux-x86_64-3.7/test
2020-10-28T16:15:17,685   copying test/test_backward.py -> build/lib.linux-x86_64-3.7/test
2020-10-28T16:15:17,685   copying test/__init__.py -> build/lib.linux-x86_64-3.7/test
2020-10-28T16:15:17,685   copying test/utils.py -> build/lib.linux-x86_64-3.7/test
2020-10-28T16:15:17,685   creating build/lib.linux-x86_64-3.7/torch_scatter
2020-10-28T16:15:17,685   copying torch_scatter/max.py -> build/lib.linux-x86_64-3.7/torch_scatter
2020-10-28T16:15:17,685   copying torch_scatter/min.py -> build/lib.linux-x86_64-3.7/torch_scatter
2020-10-28T16:15:17,685   copying torch_scatter/mean.py -> build/lib.linux-x86_64-3.7/torch_scatter
2020-10-28T16:15:17,685   copying torch_scatter/mul.py -> build/lib.linux-x86_64-3.7/torch_scatter
2020-10-28T16:15:17,685   copying torch_scatter/add.py -> build/lib.linux-x86_64-3.7/torch_scatter
2020-10-28T16:15:17,685   copying torch_scatter/std.py -> build/lib.linux-x86_64-3.7/torch_scatter
2020-10-28T16:15:17,685   copying torch_scatter/sub.py -> build/lib.linux-x86_64-3.7/torch_scatter
2020-10-28T16:15:17,685   copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.7/torch_scatter
2020-10-28T16:15:17,686   copying torch_scatter/div.py -> build/lib.linux-x86_64-3.7/torch_scatter
2020-10-28T16:15:17,686   creating build/lib.linux-x86_64-3.7/torch_scatter/utils
2020-10-28T16:15:17,686   copying torch_scatter/utils/gen.py -> build/lib.linux-x86_64-3.7/torch_scatter/utils
2020-10-28T16:15:17,686   copying torch_scatter/utils/ext.py -> build/lib.linux-x86_64-3.7/torch_scatter/utils
2020-10-28T16:15:17,686   copying torch_scatter/utils/__init__.py -> build/lib.linux-x86_64-3.7/torch_scatter/utils
2020-10-28T16:15:17,686   running build_ext
2020-10-28T16:15:17,696   building 'torch_scatter.scatter_cpu' extension
2020-10-28T16:15:17,696   creating build/temp.linux-x86_64-3.7
2020-10-28T16:15:17,696   creating build/temp.linux-x86_64-3.7/cpu
2020-10-28T16:15:17,696   gcc -pthread -B /home/jjpeng/.conda/envs/yxwang_pre1/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/jjpeng/.conda/envs/yxwang_pre1/lib/python3.7/site-packages/torch/lib/include -I/home/jjpeng/.conda/envs/yxwang_pre1/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/jjpeng/.conda/envs/yxwang_pre1/lib/python3.7/site-packages/torch/lib/include/TH -I/home/jjpeng/.conda/envs/yxwang_pre1/lib/python3.7/site-packages/torch/lib/include/THC -I/home/jjpeng/.conda/envs/yxwang_pre1/include/python3.7m -c cpu/scatter.cpp -o build/temp.linux-x86_64-3.7/cpu/scatter.o -Wno-unused-variable -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
2020-10-28T16:15:17,703   cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
2020-10-28T16:15:25,674   g++ -pthread -shared -B /home/jjpeng/.conda/envs/yxwang_pre1/compiler_compat -L/home/jjpeng/.conda/envs/yxwang_pre1/lib -Wl,-rpath=/home/jjpeng/.conda/envs/yxwang_pre1/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/cpu/scatter.o -o build/lib.linux-x86_64-3.7/torch_scatter/scatter_cpu.cpython-37m-x86_64-linux-gnu.so
2020-10-28T16:15:25,764   installing to build/bdist.linux-x86_64/wheel
2020-10-28T16:15:25,764   running install
2020-10-28T16:15:25,764   running install_lib
2020-10-28T16:15:25,765   creating build/bdist.linux-x86_64
2020-10-28T16:15:25,765   creating build/bdist.linux-x86_64/wheel
2020-10-28T16:15:25,765   creating build/bdist.linux-x86_64/wheel/test
2020-10-28T16:15:25,765   copying build/lib.linux-x86_64-3.7/test/test_std.py -> build/bdist.linux-x86_64/wheel/test
2020-10-28T16:15:25,765   copying build/lib.linux-x86_64-3.7/test/test_multi_gpu.py -> build/bdist.linux-x86_64/wheel/test
2020-10-28T16:15:25,765   copying build/lib.linux-x86_64-3.7/test/test_forward.py -> build/bdist.linux-x86_64/wheel/test
2020-10-28T16:15:25,765   copying build/lib.linux-x86_64-3.7/test/test_backward.py -> build/bdist.linux-x86_64/wheel/test
2020-10-28T16:15:25,765   copying build/lib.linux-x86_64-3.7/test/__init__.py -> build/bdist.linux-x86_64/wheel/test
2020-10-28T16:15:25,765   copying build/lib.linux-x86_64-3.7/test/utils.py -> build/bdist.linux-x86_64/wheel/test
2020-10-28T16:15:25,766   creating build/bdist.linux-x86_64/wheel/torch_scatter
2020-10-28T16:15:25,766   creating build/bdist.linux-x86_64/wheel/torch_scatter/utils
2020-10-28T16:15:25,766   copying build/lib.linux-x86_64-3.7/torch_scatter/utils/gen.py -> build/bdist.linux-x86_64/wheel/torch_scatter/utils
2020-10-28T16:15:25,766   copying build/lib.linux-x86_64-3.7/torch_scatter/utils/ext.py -> build/bdist.linux-x86_64/wheel/torch_scatter/utils
2020-10-28T16:15:25,766   copying build/lib.linux-x86_64-3.7/torch_scatter/utils/__init__.py -> build/bdist.linux-x86_64/wheel/torch_scatter/utils
2020-10-28T16:15:25,766   copying build/lib.linux-x86_64-3.7/torch_scatter/max.py -> build/bdist.linux-x86_64/wheel/torch_scatter
2020-10-28T16:15:25,766   copying build/lib.linux-x86_64-3.7/torch_scatter/min.py -> build/bdist.linux-x86_64/wheel/torch_scatter
2020-10-28T16:15:25,766   copying build/lib.linux-x86_64-3.7/torch_scatter/mean.py -> build/bdist.linux-x86_64/wheel/torch_scatter
2020-10-28T16:15:25,766   copying build/lib.linux-x86_64-3.7/torch_scatter/scatter_cpu.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/torch_scatter
2020-10-28T16:15:25,768   copying build/lib.linux-x86_64-3.7/torch_scatter/mul.py -> build/bdist.linux-x86_64/wheel/torch_scatter
2020-10-28T16:15:25,768   copying build/lib.linux-x86_64-3.7/torch_scatter/add.py -> build/bdist.linux-x86_64/wheel/torch_scatter
2020-10-28T16:15:25,768   copying build/lib.linux-x86_64-3.7/torch_scatter/std.py -> build/bdist.linux-x86_64/wheel/torch_scatter
2020-10-28T16:15:25,768   copying build/lib.linux-x86_64-3.7/torch_scatter/sub.py -> build/bdist.linux-x86_64/wheel/torch_scatter
2020-10-28T16:15:25,769   copying build/lib.linux-x86_64-3.7/torch_scatter/__init__.py -> build/bdist.linux-x86_64/wheel/torch_scatter
2020-10-28T16:15:25,769   copying build/lib.linux-x86_64-3.7/torch_scatter/div.py -> build/bdist.linux-x86_64/wheel/torch_scatter
2020-10-28T16:15:25,769   running install_egg_info
2020-10-28T16:15:25,770   running egg_info
2020-10-28T16:15:25,770   writing torch_scatter.egg-info/PKG-INFO
2020-10-28T16:15:25,770   writing dependency_links to torch_scatter.egg-info/dependency_links.txt
2020-10-28T16:15:25,770   writing top-level names to torch_scatter.egg-info/top_level.txt
2020-10-28T16:15:25,771   reading manifest file 'torch_scatter.egg-info/SOURCES.txt'
2020-10-28T16:15:25,771   reading manifest template 'MANIFEST.in'
2020-10-28T16:15:25,772   writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
2020-10-28T16:15:25,772   Copying torch_scatter.egg-info to build/bdist.linux-x86_64/wheel/torch_scatter-1.1.2-py3.7.egg-info
2020-10-28T16:15:25,773   running install_scripts
2020-10-28T16:15:25,775   adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
2020-10-28T16:15:25,775   creating build/bdist.linux-x86_64/wheel/torch_scatter-1.1.2.dist-info/WHEEL
2020-10-28T16:15:25,776   creating '/tmp/pip-wheel-wloa6idz/torch_scatter-1.1.2-cp37-cp37m-linux_x86_64.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
2020-10-28T16:15:25,776   adding 'test/__init__.py'
2020-10-28T16:15:25,776   adding 'test/test_backward.py'
2020-10-28T16:15:25,776   adding 'test/test_forward.py'
2020-10-28T16:15:25,776   adding 'test/test_multi_gpu.py'
2020-10-28T16:15:25,776   adding 'test/test_std.py'
2020-10-28T16:15:25,776   adding 'test/utils.py'
2020-10-28T16:15:25,777   adding 'torch_scatter/__init__.py'
2020-10-28T16:15:25,777   adding 'torch_scatter/add.py'
2020-10-28T16:15:25,777   adding 'torch_scatter/div.py'
2020-10-28T16:15:25,777   adding 'torch_scatter/max.py'
2020-10-28T16:15:25,777   adding 'torch_scatter/mean.py'
2020-10-28T16:15:25,777   adding 'torch_scatter/min.py'
2020-10-28T16:15:25,778   adding 'torch_scatter/mul.py'
2020-10-28T16:15:25,908   adding 'torch_scatter/scatter_cpu.cpython-37m-x86_64-linux-gnu.so'
2020-10-28T16:15:25,916   adding 'torch_scatter/std.py'
2020-10-28T16:15:25,916   adding 'torch_scatter/sub.py'
2020-10-28T16:15:25,916   adding 'torch_scatter/utils/__init__.py'
2020-10-28T16:15:25,916   adding 'torch_scatter/utils/ext.py'
2020-10-28T16:15:25,916   adding 'torch_scatter/utils/gen.py'
2020-10-28T16:15:25,916   adding 'torch_scatter-1.1.2.dist-info/LICENSE'
2020-10-28T16:15:25,917   adding 'torch_scatter-1.1.2.dist-info/METADATA'
2020-10-28T16:15:25,917   adding 'torch_scatter-1.1.2.dist-info/WHEEL'
2020-10-28T16:15:25,917   adding 'torch_scatter-1.1.2.dist-info/top_level.txt'
2020-10-28T16:15:25,917   adding 'torch_scatter-1.1.2.dist-info/RECORD'
2020-10-28T16:15:25,917   removing build/bdist.linux-x86_64/wheel
2020-10-28T16:15:25,978   Created wheel for torch-scatter: filename=torch_scatter-1.1.2-cp37-cp37m-linux_x86_64.whl size=1226577 sha256=e32d374969560f4279f4f0dd96277362ec3b1e91bf1895c4b5ae5fc103605402
2020-10-28T16:15:25,978   Stored in directory: /home/jjpeng/.cache/pip/wheels/94/b7/f5/ed396556f682099960df348299f2b33e93a41026b8b4d562d8
2020-10-28T16:15:25,978 Successfully built torch-scatter
2020-10-28T16:15:26,061 Installing collected packages: torch-scatter

2020-10-28T16:15:26,105 Successfully installed torch-scatter-1.1.2
2020-10-28T16:15:26,115 Removed build tracker: '/tmp/pip-req-tracker-4vh6j2i4'
`

I wish you can help me to sovle this problem.

Thanks!
Best wishes!

**Comment by rusty1s** [comment]
Is there any specific reason you are trying to install such an old version? Anyway, it looks like the CUDA kernels are not built. Are you missing a CUDA runtime environment? You can check that by trying to access `nvcc` via the command line.

**Comment by GeniusYx** [comment]
Thanks for your reply.
I want to run the code from [code,](https://github.com/snap-stanford/pretrain-gnns) so I prepare the environment like this.

I run the nvcc 
`
Command 'nvcc' not found, but can be installed with:
sudo apt install nvidia-cuda-toolkit
`

But I am very confused. I can get the result as follows when I test GPU is available via torch.

`Python 3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> 
`

**Comment by rusty1s** [comment]
That's because PyTorch comes with its own CUDA runtime environment, but in order to compile CUDA code you need to install a development kit. You should install the CUDA version printed out by `torch.version.cuda` from [here](https://developer.nvidia.com/cuda-toolkit).

**Comment by GeniusYx** [comment]
Thanks a lot. I will try it.

Have a nice day~

**Comment by dabaoer** [comment]
> torch.version.cuda

I have confirmed this, the installed cuda version and torch.version.cuda are the same, both are 10.0.130, are there any other possible reasons? I have checked both cuda and cudnn and there is no problem with the installation
