### ISSUE TITLE
scatter_max in cuda

### ISSUE THREAD

**Issue by yzhangee** [rusty1s/pytorch_scatter#199]
Hi, I tried to use scatter_max with src and index on cuda, but it failed. Things work well on cpu. Can you help me to figure out the reasons?

```
  File "~/anaconda3/lib/python3.7/site-packages/torch_scatter/scatter.py", line 79, in scatter_max
        out: Optional[torch.Tensor] = None,
        dim_size: Optional[int] = None) -> Tuple[torch.Tensor, torch.Tensor]:
    return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: CUDA error: invalid device function
```

This error will occur for both min and max function, the others work well on gpu. min and max can only work on cpu in my environment.

pytorch==1.7.1
torch_scatter==2.0.6

**Comment by rusty1s** [comment]
How did you install `torch-scatter`? Can you post the log during installation?

**Comment by yzhangee** [comment]
I have been using torch-scatter for several months.  I cannot get the installation log currently.

This is the first time I try scatter_max, and catter(, reduce='max'), both of them fail if the input tensor is in gpu. They work well on cpu. They 

please refer to the following.

```
>>> import torch                                                                                                                                                                                                                                                                                                              
>>> import torch_scatter
>>> print(torch_scatter.__version__)                                                                                                                                                                                                                                                                                          
2.0.6
>>> from torch_scatter import scatter_max
>>> src = torch.FloatTensor([5,1,7,2,3,2,1,3])
>>> index = torch.LongTensor([0,0,1,0,2,2,3,3])                                                                                                                                                                                                                                                                               
>>> scatter_max(src, index)
(tensor([5., 7., 3., 3.]), tensor([0, 2, 4, 7]))
>>> scatter_max(src.cuda(), index.cuda())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "~/anaconda3/lib/python3.7/site-packages/torch_scatter/scatter.py", line 79, in scatter_max
        out: Optional[torch.Tensor] = None,
        dim_size: Optional[int] = None) -> Tuple[torch.Tensor, torch.Tensor]:
    return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: CUDA error: invalid device function
```

scatter(src, index, reduce='sum') works well on cuda.

```
>>> torch_scatter.scatter(src.cuda(), index.cuda(), reduce='sum')
tensor([8., 7., 5., 4.], device='cuda:0')
```

**Comment by rusty1s** [comment]
As far as I can tell, this is induced by an installation, where CUDA kernels are not compiled correctly. It is expected that `scatter_add` works, since we use the implementation provided by PyTorch.

I guess you are not using the provided wheels, do you? Have you tried them?

**Comment by yzhangee** [comment]
The environment is pytorch 1.7.1 with cuda 10.2.

I have reinstalled torch-scatter, the problem is still there. I tried both _torch-1.7.0+cu102.html_ and _torch-1.7.1+cu102.html_

```
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.1+cu102.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.7.1+cu102.html
Collecting torch-scatter
  Using cached torch_scatter-2.0.6-cp37-cp37m-linux_x86_64.whl
Installing collected packages: torch-scatter
Successfully installed torch-scatter-2.0.6
```

**Comment by rusty1s** [comment]
Might be related to different local CUDA environement. Which one are you using?
In case you have installed (mini)conda, you can also point to the CUDA from miniconda, e.g., mine is in:
```
export LD_LIBRARY_PATH={miniconda_path}/lib:$LD_LIBRARY_PATH
```
