### ISSUE TITLE
Some Cuda Error after pip install

### ISSUE THREAD

**Issue by LeeJunHyun** [rusty1s/pytorch_scatter#23]
Hi, I really appreciate about releasing this lib and pytorch-geometric.
There was a new error that did not occur in a previous installation.

Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

```python
import torch
from torch_scatter import scatter_max
```

```sh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch_scatter/utils/ext.py", line 5, in <module>
    import torch_scatter.scatter_cuda
ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda'
```

in pytorch  '1.0.1.post2' version.

How can I fix it?

**Comment by LeeJunHyun** [comment]
FYI, I used py3.6_cuda9.0.176_cudnn7.4.2_2 with GTX1080 GPU.

**Comment by rusty1s** [comment]
Can you verify this error by installing from source?

**Comment by LeeJunHyun** [comment]
I newly built up conda virtual env using below command.

```sh
conda create -n VENV
conda activate VENV
conda install -c rdkit rdkit
conda install pytorch torchvision cudatoolkit=9.0 -c pytorch
pip install torch-scatter
```

These are all of what I did.

**Comment by rusty1s** [comment]
Yes, there sadly occurred an error in the installation of `torch-scatter` which got ignored by pip. Please clone `torch-scatter`, run `python setup.py install` and post the error log.

**Comment by LeeJunHyun** [comment]
During `python setup.py install`

```sh
running install
running bdist_egg
running egg_info
creating torch_scatter.egg-info
writing torch_scatter.egg-info/PKG-INFO
writing dependency_links to torch_scatter.egg-info/dependency_links.txt
writing top-level names to torch_scatter.egg-info/top_level.txt
writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
reading manifest file 'torch_scatter.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/test
copying test/test_backward.py -> build/lib.linux-x86_64-3.6/test
copying test/test_forward.py -> build/lib.linux-x86_64-3.6/test
copying test/utils.py -> build/lib.linux-x86_64-3.6/test
copying test/__init__.py -> build/lib.linux-x86_64-3.6/test
copying test/test_std.py -> build/lib.linux-x86_64-3.6/test
creating build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/sub.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/max.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/min.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/std.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/mul.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/mean.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/div.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter
copying torch_scatter/add.py -> build/lib.linux-x86_64-3.6/torch_scatter
creating build/lib.linux-x86_64-3.6/torch_scatter/utils
copying torch_scatter/utils/gen.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
copying torch_scatter/utils/ext.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
copying torch_scatter/utils/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
running build_ext
building 'torch_scatter.scatter_cpu' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/cpu
gcc -pthread -B /home/junhyun/.conda/envs/VENV/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch/lib/include -I/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch/lib/include/TH -I/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch/lib/include/THC -I/home/junhyun/.conda/envs/VENV/include/python3.6m -c cpu/scatter.cpp -o build/temp.linux-x86_64-3.6/cpu/scatter.o -Wno-unused-variable -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -shared -B /home/junhyun/.conda/envs/VENV/compiler_compat -L/home/junhyun/.conda/envs/VENV/lib -Wl,-rpath=/home/junhyun/.conda/envs/VENV/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/cpu/scatter.o -o build/lib.linux-x86_64-3.6/torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so
building 'torch_scatter.scatter_cuda' extension
creating build/temp.linux-x86_64-3.6/cuda
gcc -pthread -B /home/junhyun/.conda/envs/VENV/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch/lib/include -I/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch/lib/include/TH -I/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/junhyun/.conda/envs/VENV/include/python3.6m -c cuda/scatter.cpp -o build/temp.linux-x86_64-3.6/cuda/scatter.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/bin/nvcc -I/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch/lib/include -I/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch/lib/include/TH -I/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/junhyun/.conda/envs/VENV/include/python3.6m -c cuda/scatter_kernel.cu -o build/temp.linux-x86_64-3.6/cuda/scatter_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
g++ -pthread -shared -B /home/junhyun/.conda/envs/VENV/compiler_compat -L/home/junhyun/.conda/envs/VENV/lib -Wl,-rpath=/home/junhyun/.conda/envs/VENV/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/cuda/scatter.o build/temp.linux-x86_64-3.6/cuda/scatter_kernel.o -L/usr/local/cuda/lib64 -lcudart -o build/lib.linux-x86_64-3.6/torch_scatter/scatter_cuda.cpython-36m-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.6/test/test_backward.py -> build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.6/test/test_forward.py -> build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.6/test/utils.py -> build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.6/test/__init__.py -> build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.6/test/test_std.py -> build/bdist.linux-x86_64/egg/test
creating build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/sub.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/max.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/min.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/std.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/mul.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/mean.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/div.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/__init__.py -> build/bdist.linux-x86_64/egg/torch_scatter
creating build/bdist.linux-x86_64/egg/torch_scatter/utils
copying build/lib.linux-x86_64-3.6/torch_scatter/utils/gen.py -> build/bdist.linux-x86_64/egg/torch_scatter/utils
copying build/lib.linux-x86_64-3.6/torch_scatter/utils/ext.py -> build/bdist.linux-x86_64/egg/torch_scatter/utils
copying build/lib.linux-x86_64-3.6/torch_scatter/utils/__init__.py -> build/bdist.linux-x86_64/egg/torch_scatter/utils
copying build/lib.linux-x86_64-3.6/torch_scatter/scatter_cuda.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.6/torch_scatter/add.py -> build/bdist.linux-x86_64/egg/torch_scatter
byte-compiling build/bdist.linux-x86_64/egg/test/test_backward.py to test_backward.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/test/test_forward.py to test_forward.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/test/utils.py to utils.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/test/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/test/test_std.py to test_std.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/sub.py to sub.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/max.py to max.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/min.py to min.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/std.py to std.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/mul.py to mul.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/mean.py to mean.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/div.py to div.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/utils/gen.py to gen.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/utils/ext.py to ext.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/utils/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/add.py to add.cpython-36.pyc
creating stub loader for torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so
creating stub loader for torch_scatter/scatter_cuda.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/scatter_cpu.py to scatter_cpu.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/scatter_cuda.py to scatter_cuda.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_scatter.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_scatter.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_scatter.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_scatter.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
torch_scatter.__pycache__.scatter_cpu.cpython-36: module references __file__
torch_scatter.__pycache__.scatter_cuda.cpython-36: module references __file__
creating dist
creating 'dist/torch_scatter-1.1.1-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing torch_scatter-1.1.1-py3.6-linux-x86_64.egg
creating /home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch_scatter-1.1.1-py3.6-linux-x86_64.egg
Extracting torch_scatter-1.1.1-py3.6-linux-x86_64.egg to /home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages
Adding torch-scatter 1.1.1 to easy-install.pth file

Installed /home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch_scatter-1.1.1-py3.6-linux-x86_64.egg
Processing dependencies for torch-scatter==1.1.1
Finished processing dependencies for torch-scatter==1.1.1
```
But now, there are different error


Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

```python
import torch_scatter
```
```sh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/junhyun/pytorch_scatter/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home/junhyun/pytorch_scatter/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home/junhyun/pytorch_scatter/torch_scatter/utils/ext.py", line 2, in <module>
    import torch_scatter.scatter_cpu
ModuleNotFoundError: No module named 'torch_scatter.scatter_cpu'
```

**Comment by davidemaz** [comment]
@LeeJunHyun from the Traceback it seems that you are importing torch_scatter from the local directory. You shouldn't launch python or ipython from pytorch_scatter directory otherwise python will search the functions' names in the local path instead of searching in the installed packages. Try running python from another directory and check if it works.

**Comment by LeeJunHyun** [comment]
@davidemaz Thanks for your advice.
I did , but there are another error in installation.

```sh
junhyun@Ubuntu: python pytorch_scatter/setup.py install

running install
running bdist_egg
running egg_info
creating torch_scatter.egg-info
writing torch_scatter.egg-info/PKG-INFO
writing dependency_links to torch_scatter.egg-info/dependency_links.txt
writing top-level names to torch_scatter.egg-info/top_level.txt
writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
reading manifest file 'torch_scatter.egg-info/SOURCES.txt'
writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'torch_scatter.scatter_cpu' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/cpu
gcc -pthread -B /home/junhyun/.conda/envs/VENV/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch/lib/include -I/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch/lib/include/TH -I/home/junhyun/.conda/envs/VENV/lib/python3.6/site-packages/torch/lib/include/THC -I/home/junhyun/.conda/envs/VENV/include/python3.6m -c cpu/scatter.cpp -o build/temp.linux-x86_64-3.6/cpu/scatter.o -Wno-unused-variable -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
gcc: error: cpu/scatter.cpp: No such file or directory
error: command 'gcc' failed with exit status 1
```

**Comment by koustuvsinha** [comment]
Same issue on a different machine. while compiling from source no errors are seen : 

```
running install
running bdist_egg
running egg_info
writing torch_scatter.egg-info/PKG-INFO
writing dependency_links to torch_scatter.egg-info/dependency_links.txt
writing top-level names to torch_scatter.egg-info/top_level.txt
reading manifest file 'torch_scatter.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.7/test/__init__.py -> build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.7/test/test_backward.py -> build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.7/test/test_forward.py -> build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.7/test/test_std.py -> build/bdist.linux-x86_64/egg/test
copying build/lib.linux-x86_64-3.7/test/utils.py -> build/bdist.linux-x86_64/egg/test
creating build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.7/torch_scatter/__init__.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.7/torch_scatter/add.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.7/torch_scatter/div.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.7/torch_scatter/max.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.7/torch_scatter/mean.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.7/torch_scatter/min.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.7/torch_scatter/mul.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.7/torch_scatter/std.py -> build/bdist.linux-x86_64/egg/torch_scatter
copying build/lib.linux-x86_64-3.7/torch_scatter/sub.py -> build/bdist.linux-x86_64/egg/torch_scatter
creating build/bdist.linux-x86_64/egg/torch_scatter/utils
copying build/lib.linux-x86_64-3.7/torch_scatter/utils/__init__.py -> build/bdist.linux-x86_64/egg/torch_scatter/utils
copying build/lib.linux-x86_64-3.7/torch_scatter/utils/ext.py -> build/bdist.linux-x86_64/egg/torch_scatter/utils
copying build/lib.linux-x86_64-3.7/torch_scatter/utils/gen.py -> build/bdist.linux-x86_64/egg/torch_scatter/utils
copying build/lib.linux-x86_64-3.7/torch_scatter/scatter_cpu.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/torch_scatter
byte-compiling build/bdist.linux-x86_64/egg/test/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/test/test_backward.py to test_backward.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/test/test_forward.py to test_forward.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/test/test_std.py to test_std.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/test/utils.py to utils.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/add.py to add.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/div.py to div.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/max.py to max.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/mean.py to mean.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/min.py to min.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/mul.py to mul.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/std.py to std.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/sub.py to sub.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/utils/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/utils/ext.py to ext.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/utils/gen.py to gen.cpython-37.pyc
creating stub loader for torch_scatter/scatter_cpu.cpython-37m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/torch_scatter/scatter_cpu.py to scatter_cpu.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_scatter.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_scatter.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_scatter.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_scatter.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
torch_scatter.__pycache__.scatter_cpu.cpython-37: module references __file__
creating 'dist/torch_scatter-1.1.1-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing torch_scatter-1.1.1-py3.7-linux-x86_64.egg
creating /private/home/koustuvs/miniconda3/envs/test_p/lib/python3.7/site-packages/torch_scatter-1.1.1-py3.7-linux-x86_64.egg
Extracting torch_scatter-1.1.1-py3.7-linux-x86_64.egg to /private/home/koustuvs/miniconda3/envs/test_p/lib/python3.7/site-packages
Adding torch-scatter 1.1.1 to easy-install.pth file

Installed /private/home/koustuvs/miniconda3/envs/test_p/lib/python3.7/site-packages/torch_scatter-1.1.1-py3.7-linux-x86_64.egg
Processing dependencies for torch-scatter==1.1.1
Finished processing dependencies for torch-scatter==1.1.1
```

yet both on source install and `pip install` I get the above error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/home/koustuvs/miniconda3/envs/test_p/lib/python3.7/site-packages/torch_scatter-1.1.1-py3.7-linux-x86_64.egg/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/private/home/koustuvs/miniconda3/envs/test_p/lib/python3.7/site-packages/torch_scatter-1.1.1-py3.7-linux-x86_64.egg/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/private/home/koustuvs/miniconda3/envs/test_p/lib/python3.7/site-packages/torch_scatter-1.1.1-py3.7-linux-x86_64.egg/torch_scatter/utils/ext.py", line 5, in <module>
    import torch_scatter.scatter_cuda
ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda'
```

Any ideas? this is on cuda 10.0, ubuntu 18.04

**Comment by koustuvsinha** [comment]
fixed the issue. I missed the instructions on the readme - make sure your path contains cuda binary!
