### ISSUE TITLE
scatter_max/min GPU on Windows return 0s

### ISSUE THREAD

**Issue by steveazzolin** [rusty1s/pytorch_scatter#263]
Hi all,

I have found several GitHub issues related to `scatter_max`, but I have not found anything related to my problem (I apologize if I haven't searched deep enough).

When I run `scatter_max` or `scatter_min` on a GPU tensor the result gets collapsed into a 0 matrix, while by using the CPU it works fine. The problem emerged when I was pooling the final node representations of a GNN with a `global_max_pooling` layer in PyG, which resulted in a network that was not learning anything. 

```
import torch
from torch_scatter import scatter

src = torch.randn(10, 6, 64)
index = torch.tensor([0, 1, 0, 1, 2, 1])

out = scatter(src, index, dim=1, reduce="max")
out2 = scatter(src.to("cuda"), index.to("cuda"), dim=1, reduce="max")

print(out[0,:5,:5] , "\n" , out2[0,:5,:5], "\n\n")

out = scatter(src, index, dim=1, reduce="min")
out2 = scatter(src.to("cuda"), index.to("cuda"), dim=1, reduce="min")
print(out[0,:5,:5] , "\n" , out2[0,:5,:5], "\n\n")

out = scatter(src, index, dim=1, reduce="mean")
out2 = scatter(src.to("cuda"), index.to("cuda"), dim=1, reduce="mean")
print(out[0,:5,:5] , "\n" , out2[0,:5,:5], "\n\n")
```

The output is:
```
tensor([[ 2.8089, -0.5243,  0.6746,  0.7766,  1.5888],
        [ 0.8068,  1.4081,  0.7199,  0.9214,  1.0587],
        [ 0.0626,  1.8780,  0.5769, -0.6487,  0.2044]]) 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], device='cuda:0') 


tensor([[-1.1039, -0.7422, -1.1144, -0.3920,  0.2185],
        [-1.7818, -1.2782, -0.3380, -1.0124, -0.0272],
        [ 0.0626,  1.8780,  0.5769, -0.6487,  0.2044]]) 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], device='cuda:0') 


tensor([[ 0.8525, -0.6332, -0.2199,  0.1923,  0.9037],
        [-0.1209, -0.1518,  0.3331,  0.0457,  0.6503],
        [ 0.0626,  1.8780,  0.5769, -0.6487,  0.2044]]) 
 tensor([[ 0.8525, -0.6332, -0.2199,  0.1923,  0.9037],
        [-0.1209, -0.1518,  0.3331,  0.0457,  0.6503],
        [ 0.0626,  1.8780,  0.5769, -0.6487,  0.2044]], device='cuda:0') 
```

I am running on a Windows 10 machine with a 4GB GeForce GTX 1650 CUDA 11.2
`torch_scatter` version is '2.0.9'

I "resolved" by using `global_max_pooling` in my GNN, but as you can imagine it is just a workaround.

**Comment by rusty1s** [comment]
Can you say something about how you did install `torch-scatter`? What's the output of
```
pip uninstall torch-scatter
pip uninstall torch-scatter
pip install --verbose --no-cache-dir torch-scatter
```

**Comment by steveazzolin** [comment]
For my working installation I used Conda. From a clean environment I fired:

```
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
conda install pyg -c pyg -c conda-forge
```

The outputs of your commands are:

`pip uninstall torch-scatter`

```
(gnn_clone) C:\WINDOWS\system32>pip uninstall torch-scatter
Found existing installation: torch-scatter 2.0.9
Uninstalling torch-scatter-2.0.9:
  Would remove:
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\*
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\torch_scatter-2.0.9.dist-info\*
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\torch_scatter\*
  Would not remove (might be manually added):
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_add.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_basis.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_cat.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_coalesce.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_conv.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_convert.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_diag.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_ego_sample.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_eye.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_fps.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_graclus.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_grid.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_knn.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_matmul.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_metis.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_nearest.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_overload.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_permute.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_radius.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_rw.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_saint.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_sample.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_sampler.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_spmm.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_spspmm.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_storage.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_tensor.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_transpose.py
    c:\users\steve\anaconda3\envs\gnn_clone\lib\site-packages\test\test_weighting.py
Proceed (Y/n)? y
  Successfully uninstalled torch-scatter-2.0.9
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
    status = self.run(options, args)
  File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\pip\_internal\commands\uninstall.py", line 97, in run
    uninstall_pathset.commit()
  File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\pip\_internal\req\req_uninstall.py", line 436, in commit
    self._moved_paths.commit()
  File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\pip\_internal\req\req_uninstall.py", line 287, in commit
    save_dir.cleanup()
  File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\pip\_internal\utils\temp_dir.py", line 184, in cleanup
    rmtree(self._path)
  File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 326, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 406, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 409, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\pip\_internal\utils\misc.py", line 135, in rmtree
    shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
  File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Accesso negato: 'c:\\users\\steve\\anaconda3\\envs\\gnn_clone\\lib\\site-packages\\~-rch_scatter\\_scatter_cuda.pyd'

```



For `pip install --verbose --no-cache-dir torch-scatter` instead:

```
(gnn_clone) C:\WINDOWS\system32>pip install --verbose --no-cache-dir torch-scatter
Using pip 21.2.4 from C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\pip (python 3.7)
Collecting torch-scatter
  Downloading torch_scatter-2.0.9.tar.gz (21 kB)
    Running command python setup.py egg_info
    running egg_info
    creating C:\Users\Steve\AppData\Local\Temp\pip-pip-egg-info-sd05fxm4\torch_scatter.egg-info
    writing C:\Users\Steve\AppData\Local\Temp\pip-pip-egg-info-sd05fxm4\torch_scatter.egg-info\PKG-INFO
    writing dependency_links to C:\Users\Steve\AppData\Local\Temp\pip-pip-egg-info-sd05fxm4\torch_scatter.egg-info\dependency_links.txt
    writing requirements to C:\Users\Steve\AppData\Local\Temp\pip-pip-egg-info-sd05fxm4\torch_scatter.egg-info\requires.txt
    writing top-level names to C:\Users\Steve\AppData\Local\Temp\pip-pip-egg-info-sd05fxm4\torch_scatter.egg-info\top_level.txt
    writing manifest file 'C:\Users\Steve\AppData\Local\Temp\pip-pip-egg-info-sd05fxm4\torch_scatter.egg-info\SOURCES.txt'
    reading manifest file 'C:\Users\Steve\AppData\Local\Temp\pip-pip-egg-info-sd05fxm4\torch_scatter.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\setuptools\dist.py:720: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
      % (opt, underscore_opt)
    warning: no previously-included files matching '*' found under directory 'test'
    adding license file 'LICENSE'
    writing manifest file 'C:\Users\Steve\AppData\Local\Temp\pip-pip-egg-info-sd05fxm4\torch_scatter.egg-info\SOURCES.txt'
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
        return stream.closed
    ValueError: underlying buffer has been detached
Building wheels for collected packages: torch-scatter
  Running command 'C:\Users\Steve\anaconda3\envs\gnn_clone\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Steve\\AppData\\Local\\Temp\\pip-install-f5u55e5t\\torch-scatter_5e9d27078f2b4d8aaf2f7fad9f847982\\setup.py'"'"'; __file__='"'"'C:\\Users\\Steve\\AppData\\Local\\Temp\\pip-install-f5u55e5t\\torch-scatter_5e9d27078f2b4d8aaf2f7fad9f847982\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Steve\AppData\Local\Temp\pip-wheel-dnfbzwhi'
  C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\setuptools\dist.py:720: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    % (opt, underscore_opt)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\torch_scatter
  copying torch_scatter\placeholder.py -> build\lib.win-amd64-3.7\torch_scatter
  copying torch_scatter\scatter.py -> build\lib.win-amd64-3.7\torch_scatter
  copying torch_scatter\segment_coo.py -> build\lib.win-amd64-3.7\torch_scatter
  copying torch_scatter\segment_csr.py -> build\lib.win-amd64-3.7\torch_scatter
  copying torch_scatter\utils.py -> build\lib.win-amd64-3.7\torch_scatter
  copying torch_scatter\__init__.py -> build\lib.win-amd64-3.7\torch_scatter
  creating build\lib.win-amd64-3.7\torch_scatter\composite
  copying torch_scatter\composite\logsumexp.py -> build\lib.win-amd64-3.7\torch_scatter\composite
  copying torch_scatter\composite\softmax.py -> build\lib.win-amd64-3.7\torch_scatter\composite
  copying torch_scatter\composite\std.py -> build\lib.win-amd64-3.7\torch_scatter\composite
  copying torch_scatter\composite\__init__.py -> build\lib.win-amd64-3.7\torch_scatter\composite
  running build_ext
  C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\torch\utils\cpp_extension.py:316: UserWarning: Error checking compiler version for cl: [WinError 2] Impossibile trovare il file specificato
    warnings.warn(f'Error checking compiler version for {compiler}: {error}')
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Steve\AppData\Local\Temp\pip-install-f5u55e5t\torch-scatter_5e9d27078f2b4d8aaf2f7fad9f847982\setup.py", line 102, in <module>
      packages=find_packages(),
    File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\torch\utils\cpp_extension.py", line 404, in build_extensions
      self._check_cuda_version()
    File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\torch\utils\cpp_extension.py", line 781, in _check_cuda_version
      raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
  RuntimeError:
  The detected CUDA version (10.1) mismatches the version that was used to compile
  PyTorch (11.3). Please make sure to use the same CUDA versions.

  Error in atexit._run_exitfuncs:
  Traceback (most recent call last):
    File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
      return stream.closed
  ValueError: underlying buffer has been detached
  Building wheel for torch-scatter (setup.py) ... error
  ERROR: Failed building wheel for torch-scatter
  Running setup.py clean for torch-scatter
  Running command 'C:\Users\Steve\anaconda3\envs\gnn_clone\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Steve\\AppData\\Local\\Temp\\pip-install-f5u55e5t\\torch-scatter_5e9d27078f2b4d8aaf2f7fad9f847982\\setup.py'"'"'; __file__='"'"'C:\\Users\\Steve\\AppData\\Local\\Temp\\pip-install-f5u55e5t\\torch-scatter_5e9d27078f2b4d8aaf2f7fad9f847982\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
  C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\setuptools\dist.py:720: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    % (opt, underscore_opt)
  running clean
  removing 'build\lib.win-amd64-3.7' (and everything under it)
  'build\bdist.win-amd64' does not exist -- can't clean it
  'build\scripts-3.7' does not exist -- can't clean it
  removing 'build'
  Error in atexit._run_exitfuncs:
  Traceback (most recent call last):
    File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
      return stream.closed
  ValueError: underlying buffer has been detached
Failed to build torch-scatter
Installing collected packages: torch-scatter
    Running command 'C:\Users\Steve\anaconda3\envs\gnn_clone\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Steve\\AppData\\Local\\Temp\\pip-install-f5u55e5t\\torch-scatter_5e9d27078f2b4d8aaf2f7fad9f847982\\setup.py'"'"'; __file__='"'"'C:\\Users\\Steve\\AppData\\Local\\Temp\\pip-install-f5u55e5t\\torch-scatter_5e9d27078f2b4d8aaf2f7fad9f847982\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Steve\AppData\Local\Temp\pip-record-y46u3afd\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Steve\anaconda3\envs\gnn_clone\Include\torch-scatter'
    C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\setuptools\dist.py:720: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
      % (opt, underscore_opt)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\torch_scatter
    copying torch_scatter\placeholder.py -> build\lib.win-amd64-3.7\torch_scatter
    copying torch_scatter\scatter.py -> build\lib.win-amd64-3.7\torch_scatter
    copying torch_scatter\segment_coo.py -> build\lib.win-amd64-3.7\torch_scatter
    copying torch_scatter\segment_csr.py -> build\lib.win-amd64-3.7\torch_scatter
    copying torch_scatter\utils.py -> build\lib.win-amd64-3.7\torch_scatter
    copying torch_scatter\__init__.py -> build\lib.win-amd64-3.7\torch_scatter
    creating build\lib.win-amd64-3.7\torch_scatter\composite
    copying torch_scatter\composite\logsumexp.py -> build\lib.win-amd64-3.7\torch_scatter\composite
    copying torch_scatter\composite\softmax.py -> build\lib.win-amd64-3.7\torch_scatter\composite
    copying torch_scatter\composite\std.py -> build\lib.win-amd64-3.7\torch_scatter\composite
    copying torch_scatter\composite\__init__.py -> build\lib.win-amd64-3.7\torch_scatter\composite
    running build_ext
    C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\torch\utils\cpp_extension.py:316: UserWarning: Error checking compiler version for cl: [WinError 2] Impossibile trovare il file specificato
      warnings.warn(f'Error checking compiler version for {compiler}: {error}')
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Steve\AppData\Local\Temp\pip-install-f5u55e5t\torch-scatter_5e9d27078f2b4d8aaf2f7fad9f847982\setup.py", line 102, in <module>
        packages=find_packages(),
      File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
        _build_ext.run(self)
      File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\torch\utils\cpp_extension.py", line 404, in build_extensions
        self._check_cuda_version()
      File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\torch\utils\cpp_extension.py", line 781, in _check_cuda_version
        raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
    RuntimeError:
    The detected CUDA version (10.1) mismatches the version that was used to compile
    PyTorch (11.3). Please make sure to use the same CUDA versions.

    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "C:\Users\Steve\anaconda3\envs\gnn_clone\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
        return stream.closed
    ValueError: underlying buffer has been detached
    Running setup.py install for torch-scatter ... error
ERROR: Command errored out with exit status 1: 'C:\Users\Steve\anaconda3\envs\gnn_clone\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Steve\\AppData\\Local\\Temp\\pip-install-f5u55e5t\\torch-scatter_5e9d27078f2b4d8aaf2f7fad9f847982\\setup.py'"'"'; __file__='"'"'C:\\Users\\Steve\\AppData\\Local\\Temp\\pip-install-f5u55e5t\\torch-scatter_5e9d27078f2b4d8aaf2f7fad9f847982\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Steve\AppData\Local\Temp\pip-record-y46u3afd\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Steve\anaconda3\envs\gnn_clone\Include\torch-scatter' Check the logs for full command output.
```

**Comment by rusty1s** [comment]
I see. Looks like you have a local CUDA version (10.1) while you installed PyTorch with CUDA 11.3. I think you either need to
* like CUDA to the package installed by `conda` (the one that comes with PyTorch), or
* downgrade PyTorch to use CUDA 10.1

**Comment by steveazzolin** [comment]
I see, but is strange because if I run `nvidia-smi` I get:

![image](https://user-images.githubusercontent.com/53196079/150751762-9a0c2bee-eb4c-45b6-85ef-2b9c436c7cdc.png)


So, the CUDA version seems to be 11.2

**Comment by rusty1s** [comment]
Weird :) What's the output of `ls /usr/local` (or the alternative path in which Windows stores CUDA )? I guess there may be multiple CUDA versions installed which might lead to this conflict.
