### ISSUE TITLE
Issues from importing `torch` in `setup.py`

### ISSUE THREAD

**Issue by cthoyt** [rusty1s/pytorch_scatter#265]
As we all know, dealing with C extensions is pretty unruly and it's nice that `setup.py` is flexible in this regard. However, because this package's `setup.py` imports PyTorch, it causes all sorts of havoc with downstream code when you include `torch_scatter` in your own requirements. This usually leads to instructions to iteratively (manually) install PyTorch then some downstream stuff.

I think there's a solution available to alleviate this: use a `pyproject.toml` to specify build requirements so you can simply pip install this package without `torch` already installed. This was demonstrated for a different kind of package in https://github.com/kivy/pyjnius/pull/594

I'll submit a PR to demonstate

**Comment by rusty1s** [comment]
Thanks for this issue. I understand that this works for `Cython`, but I am unsure what exactly happens in the PyTorch case?

For example, given the `requirement.txt`:
```
torch==1.10.0+cu102
torch-scatter
```
Does `torch-scatter` install C extensions based on `torch==1.10.0+cu102` or based on which CUDA depdendency?

Do you think we can make this work for PyTorch due to the differences in CUDA requirements? In my experience, forcing a specific PyTorch+CUDA combination causes more harm than good.

**Comment by cthoyt** [comment]
I think this would be up to the dependency resolver in `pip` (introduced in 2020) to handle - the PR demonstration I made doesn't pin the version of `torch` in the installation of `torch-scatter`, so it should respect other requirements that are given at the same time and/or the preexisting installation (meaning a potential improvement here doesn't mean anyone has to change the way they're doing anything)

**Comment by rusty1s** [comment]
I understand that. I think most people are installing from wheel anyway, which works just fine in a single `requirement.txt` file or via `conda`. For users of `pip install torch-scatter`, I think it is actually better to let installation fail in case PyTorch is not installed than to install an arbitrary PyTorch+CUDA version. This likely results in errors as the default CUDA version of PyTorch and the system CUDA do not necessarily match.

**Comment by a-gn** [comment]
> I understand that. I think most people are installing from wheel anyway, which works just fine in a single `requirement.txt` file or via `conda`. For users of `pip install torch-scatter` (which means manually compiling via `nvcc`), I think it is actually better to let installation fail in case PyTorch is not installed than to install an arbitrary PyTorch+CUDA version. This likely results in errors as the default CUDA version of PyTorch and the system CUDA do not necessarily match.

Hello, we use torch-scatter in multiple deployments and we would benefit from declaring the torch build dependency in `pyproject.toml`.

We have a lockfile containing precise dependency versions (maintained with [pip-tools](https://github.com/jazzband/pip-tools)). The goal is to be able to install all 100+ dependencies in one command with `pip install -r requirements.txt`. `requirements.txt` does contain the version of PyTorch/CUDA we want, **but pip does not install torch before torch-scatter**, because torch is not a _build-time_ dependency of torch-scatter. Hence the install fails.

Installing in two steps would mean extracting the torch version constraint and index-url from our lockfile (along with all its dependencies), installing that, then installing the rest, including torch-scatter. You see that this complicates deployment when multiple environments and deployment systems are concerned. We had to copy the torch-scatter code in our internal repository and add a `pyproject.toml` there, but that complicates upgrades and requires passing that local path to pip.

I see your problem with pip silently installing a CPU version of torch when the user does not explicitly provide a torch version. I think it's more important that torch-scatter installs correctly when we give pip a complete set of dependencies, than to crash on a user error. Could we maybe add a warning in `setup.py` to tell the user to check which torch version is being installed?

FYI, our `pyproject.toml` is:

```toml
[build-system]
requires = [
  "setuptools",
  "torch",
  "wheel",
]
build-backend = "setuptools.build_meta"
```

I can open a PR if you're OK with this method.

**Comment by rusty1s** [comment]
You can install via `requirements.txt` file by installing from wheels. For example,
```
-f https://data.pyg.org/whl/torch-1.12.1+cu116.html
torch-scatter==2.0.9

**Comment by a-gn** [comment]
> You can install via `requirements.txt` file by linking to the wheels. For example,
> 
> ```
> -f https://data.pyg.org/whl/torch-1.12.1+cu116.html
> torch-scatter==2.0.9
> ```

I see, the problem is that we were using PyTorch 1.8.3 LTS and there's no matching torch-scatter build. We will see if we can upgrade to a torch version you support. Thanks!

**Comment by rusty1s** [comment]
You can also use the wheels for `1.8.0` for PyTorch `1.8.3`.

**Comment by rusty1s** [comment]
Mh, this works just fine on my end. On which OS do you run this query? Does `-f https://data.pyg.org/whl/torch-2.0.0+cpu.html` actually get picked up (you can confirm by running via pip install --verbose`)? It looks like it tries to install the package from source.

**Comment by Andrew-S-Rosen** [comment]
I can confirm this is still an issue. The user gets back something like:

```
  × Failed to build `torch-scatter==2.1.2`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit
      status: 1)

      [stderr]
      Traceback (most recent call last):
        File "<string>", line 14, in <module>
        File
      "/home/runner/.cache/uv/builds-v0/.tmpXjIkz9/lib/python3.12/site-packages/setuptools/build_meta.py",
      line 331, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File
      "/home/runner/.cache/uv/builds-v0/.tmpXjIkz9/lib/python3.12/site-packages/setuptools/build_meta.py",
      line 301, in _get_build_requires
          self.run_setup()
        File
      "/home/runner/.cache/uv/builds-v0/.tmpXjIkz9/lib/python3.12/site-packages/setuptools/build_meta.py",
      line 512, in run_setup
          super().run_setup(setup_script=setup_script)
        File
      "/home/runner/.cache/uv/builds-v0/.tmpXjIkz9/lib/python3.12/site-packages/setuptools/build_meta.py",
      line 317, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'torch'

      hint: This error likely indicates that `torch-scatter@2.1.2`
      depends on `torch`, but doesn't declare it as a build dependency.
      If `torch-scatter` is a first-party package, consider adding `torch`
      to its `build-system.requires`. Otherwise, either add it to your
      `pyproject.toml` under:

      [tool.uv.extra-build-dependencies]
      torch-scatter = ["torch"]

      or `uv pip install torch` into the environment and re-run with
      `--no-build-isolation`.
  help: `torch-scatter` (v2.1.2) was included because `newtonnet` (v2.0.1)
        depends on `torch-scatter`
```

**Comment by ramet** [comment]
As for torch-scatter, it can be installed using `--no-build-isolation`.
