### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by yongkangzhao** [rusty1s/pytorch_scatter#284]
need some guidance on how to install.

installation is giving me the error below:

I tried:
* pip install with multiple versions
* clone the repository and pip install with the repository

Thanks!

docker environment:
```
FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime
RUN apt-get update
COPY environment.yml environment.yml
RUN conda env create -f environment.yml
RUN conda init
ENV PATH /opt/conda/envs/env/bin:$PATH
RUN /bin/bash -c "source activate env"
RUN python -m spacy download en_core_web_sm
CMD python
```

environment.yml:
```
name: env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - setuptools
  - pymongo
  - spacy
  - click<8.1
  - python=3.9
  - pandas
  - optuna
  - jupyter
  - pymongo
  - pandas
  - lightgbm
  - spacy
  - tqdm
  - scikit-learn-intelex
  - optuna
  - tqdm
  - plotly
  - pip
  - pytorch
  - torchvision 
  - torchaudio 
  - cudatoolkit=11.3
  - pip:
      - kaleido
      - ordered-set


```

error message

```
$ git clone https://github.com/rusty1s/pytorch_scatter.git
Cloning into 'pytorch_scatter'...
$ pip install ./pytorch_scatter
Processing ./pytorch_scatter
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: torch-scatter
  Building wheel for torch-scatter (setup.py): started
  Building wheel for torch-scatter (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [88 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/torch_scatter
      copying torch_scatter/placeholder.py -> build/lib.linux-x86_64-3.9/torch_scatter
      copying torch_scatter/segment_csr.py -> build/lib.linux-x86_64-3.9/torch_scatter
      copying torch_scatter/utils.py -> build/lib.linux-x86_64-3.9/torch_scatter
      copying torch_scatter/scatter.py -> build/lib.linux-x86_64-3.9/torch_scatter
      copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.9/torch_scatter
      copying torch_scatter/segment_coo.py -> build/lib.linux-x86_64-3.9/torch_scatter
      creating build/lib.linux-x86_64-3.9/test
      copying test/test_zero_tensors.py -> build/lib.linux-x86_64-3.9/test
      copying test/test_scatter.py -> build/lib.linux-x86_64-3.9/test
      copying test/test_broadcasting.py -> build/lib.linux-x86_64-3.9/test
      copying test/test_segment.py -> build/lib.linux-x86_64-3.9/test
      copying test/utils.py -> build/lib.linux-x86_64-3.9/test
      copying test/test_multi_gpu.py -> build/lib.linux-x86_64-3.9/test
      copying test/__init__.py -> build/lib.linux-x86_64-3.9/test
      copying test/test_gather.py -> build/lib.linux-x86_64-3.9/test
      creating build/lib.linux-x86_64-3.9/torch_scatter/composite
      copying torch_scatter/composite/std.py -> build/lib.linux-x86_64-3.9/torch_scatter/composite
      copying torch_scatter/composite/logsumexp.py -> build/lib.linux-x86_64-3.9/torch_scatter/composite
      copying torch_scatter/composite/softmax.py -> build/lib.linux-x86_64-3.9/torch_scatter/composite
      copying torch_scatter/composite/__init__.py -> build/lib.linux-x86_64-3.9/torch_scatter/composite
      running egg_info
      creating torch_scatter.egg-info
      writing torch_scatter.egg-info/PKG-INFO
      writing dependency_links to torch_scatter.egg-info/dependency_links.txt
      writing requirements to torch_scatter.egg-info/requires.txt
      writing top-level names to torch_scatter.egg-info/top_level.txt
      writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
      reading manifest file 'torch_scatter.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/builds/cookieyong/env/pytorch_scatter/setup.py", line 97, in <module>
          setup(
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/opt/conda/envs/env/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line [339](https://gitlab.com/cookieyong/env/-/jobs/2267350084#L339), in run
          self.build_extensions()
        File "/opt/conda/envs/env/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line [396](https://gitlab.com/cookieyong/env/-/jobs/2267350084#L396), in build_extensions
          self._check_abi()
        File "/opt/conda/envs/env/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 767, in _check_abi
          check_compiler_abi_compatibility(compiler)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 300, in check_compiler_abi_compatibility
          if not check_compiler_ok_for_platform(compiler):
        File "/opt/conda/envs/env/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 257, in check_compiler_ok_for_platform
          which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
        File "/opt/conda/envs/env/lib/python3.9/subprocess.py", line [424](https://gitlab.com/cookieyong/env/-/jobs/2267350084#L424), in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/opt/conda/envs/env/lib/python3.9/subprocess.py", line [528](https://gitlab.com/cookieyong/env/-/jobs/2267350084#L528), in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torch-scatter
  Running setup.py clean for torch-scatter
Failed to build torch-scatter
Installing collected packages: torch-scatter
  Running setup.py install for torch-scatter: started
  Running setup.py install for torch-scatter: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Running setup.py install for torch-scatter did not run successfully.
  │ exit code: 1
  ╰─> [90 lines of output]
      running install
      /opt/conda/envs/env/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/torch_scatter
      copying torch_scatter/placeholder.py -> build/lib.linux-x86_64-3.9/torch_scatter
      copying torch_scatter/segment_csr.py -> build/lib.linux-x86_64-3.9/torch_scatter
      copying torch_scatter/utils.py -> build/lib.linux-x86_64-3.9/torch_scatter
      copying torch_scatter/scatter.py -> build/lib.linux-x86_64-3.9/torch_scatter
      copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.9/torch_scatter
      copying torch_scatter/segment_coo.py -> build/lib.linux-x86_64-3.9/torch_scatter
      creating build/lib.linux-x86_64-3.9/test
      copying test/test_zero_tensors.py -> build/lib.linux-x86_64-3.9/test
      copying test/test_scatter.py -> build/lib.linux-x86_64-3.9/test
      copying test/test_broadcasting.py -> build/lib.linux-x86_64-3.9/test
      copying test/test_segment.py -> build/lib.linux-x86_64-3.9/test
      copying test/utils.py -> build/lib.linux-x86_64-3.9/test
      copying test/test_multi_gpu.py -> build/lib.linux-x86_64-3.9/test
      copying test/__init__.py -> build/lib.linux-x86_64-3.9/test
      copying test/test_gather.py -> build/lib.linux-x86_64-3.9/test
      creating build/lib.linux-x86_64-3.9/torch_scatter/composite
      copying torch_scatter/composite/std.py -> build/lib.linux-x86_64-3.9/torch_scatter/composite
      copying torch_scatter/composite/logsumexp.py -> build/lib.linux-x86_64-3.9/torch_scatter/composite
      copying torch_scatter/composite/softmax.py -> build/lib.linux-x86_64-3.9/torch_scatter/composite
      copying torch_scatter/composite/__init__.py -> build/lib.linux-x86_64-3.9/torch_scatter/composite
      running egg_info
      writing torch_scatter.egg-info/PKG-INFO
      writing dependency_links to torch_scatter.egg-info/dependency_links.txt
      writing requirements to torch_scatter.egg-info/requires.txt
      writing top-level names to torch_scatter.egg-info/top_level.txt
      reading manifest file 'torch_scatter.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/builds/cookieyong/env/pytorch_scatter/setup.py", line 97, in <module>
          setup(
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 670, in run
          self.run_command('build')
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "/opt/conda/envs/env/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 396, in build_extensions
          self._check_abi()
        File "/opt/conda/envs/env/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 767, in _check_abi
          check_compiler_abi_compatibility(compiler)
        File "/opt/conda/envs/env/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 300, in check_compiler_abi_compatibility
          if not check_compiler_ok_for_platform(compiler):
        File "/opt/conda/envs/env/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 257, in check_compiler_ok_for_platform
          which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
        File "/opt/conda/envs/env/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/opt/conda/envs/env/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> torch-scatter
note: This is an issue with the package mentioned above, not pip.
```

**Comment by rusty1s** [comment]
Any reason you want to compile from source? Sadly, the error message is not very meaningful. Can you post the log when running via `pip install --verbose ...`?

**Comment by yongkangzhao** [comment]
Thanks!
I have no reason to compile from source, other than trying to get it to work. :)
I have also attempted pip install pytorch_scatter.
here is the verbose version
```
Using pip 22.0.4 from /opt/conda/envs/env/lib/python3.9/site-packages/pip (python 3.9)
Processing ./pytorch_scatter
  Preparing metadata (setup.py): started
  Running command python setup.py egg_info
  running egg_info
  creating /tmp/pip-pip-egg-info-_qri4gcg/torch_scatter.egg-info
  writing /tmp/pip-pip-egg-info-_qri4gcg/torch_scatter.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-_qri4gcg/torch_scatter.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-_qri4gcg/torch_scatter.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-_qri4gcg/torch_scatter.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-_qri4gcg/torch_scatter.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-_qri4gcg/torch_scatter.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-_qri4gcg/torch_scatter.egg-info/SOURCES.txt'
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: torch-scatter
  Building wheel for torch-scatter (setup.py): started
  Running command python setup.py bdist_wheel
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/torch_scatter
  copying torch_scatter/placeholder.py -> build/lib.linux-x86_64-3.9/torch_scatter
  copying torch_scatter/segment_csr.py -> build/lib.linux-x86_64-3.9/torch_scatter
  copying torch_scatter/utils.py -> build/lib.linux-x86_64-3.9/torch_scatter
  copying torch_scatter/scatter.py -> build/lib.linux-x86_64-3.9/torch_scatter
  copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.9/torch_scatter
  copying torch_scatter/segment_coo.py -> build/lib.linux-x86_64-3.9/torch_scatter
  creating build/lib.linux-x86_64-3.9/test
  copying test/test_zero_tensors.py -> build/lib.linux-x86_64-3.9/test
  copying test/test_scatter.py -> build/lib.linux-x86_64-3.9/test
  copying test/test_broadcasting.py -> build/lib.linux-x86_64-3.9/test
  copying test/test_segment.py -> build/lib.linux-x86_64-3.9/test
  copying test/utils.py -> build/lib.linux-x86_64-3.9/test
  copying test/test_multi_gpu.py -> build/lib.linux-x86_64-3.9/test
  copying test/__init__.py -> build/lib.linux-x86_64-3.9/test
  copying test/test_gather.py -> build/lib.linux-x86_64-3.9/test
  creating build/lib.linux-x86_64-3.9/torch_scatter/composite
  copying torch_scatter/composite/std.py -> build/lib.linux-x86_64-3.9/torch_scatter/composite
  copying torch_scatter/composite/logsumexp.py -> build/lib.linux-x86_64-3.9/torch_scatter/composite
  copying torch_scatter/composite/softmax.py -> build/lib.linux-x86_64-3.9/torch_scatter/composite
  copying torch_scatter/composite/__init__.py -> build/lib.linux-x86_64-3.9/torch_scatter/composite
  running egg_info
  creating torch_scatter.egg-info
  writing torch_scatter.egg-info/PKG-INFO
  writing dependency_links to torch_scatter.egg-info/dependency_links.txt
  writing requirements to torch_scatter.egg-info/requires.txt
  writing top-level names to torch_scatter.egg-info/top_level.txt
  writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
  reading manifest file 'torch_scatter.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/builds/cookieyong/env/pytorch_scatter/setup.py", line 97, in <module>
      setup(
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
      super().run_command(command)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/opt/conda/envs/env/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
      super().run_command(command)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
      super().run_command(command)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/opt/conda/envs/env/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 396, in build_extensions
      self._check_abi()
    File "/opt/conda/envs/env/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 767, in _check_abi
      check_compiler_abi_compatibility(compiler)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 300, in check_compiler_abi_compatibility
      if not check_compiler_ok_for_platform(compiler):
    File "/opt/conda/envs/env/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 257, in check_compiler_ok_for_platform
      which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
    File "/opt/conda/envs/env/lib/python3.9/subprocess.py", line 424, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/opt/conda/envs/env/lib/python3.9/subprocess.py", line 528, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /opt/conda/envs/env/bin/python3.9 -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize
  
  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__
  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/builds/cookieyong/env/pytorch_scatter/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' bdist_wheel -d /tmp/pip-wheel-361flceq
  cwd: /builds/cookieyong/env/pytorch_scatter/
  Building wheel for torch-scatter (setup.py): finished with status 'error'
  ERROR: Failed building wheel for torch-scatter
  Running setup.py clean for torch-scatter
  Running command python setup.py clean
  running clean
  removing 'build/lib.linux-x86_64-3.9' (and everything under it)
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.9' does not exist -- can't clean it
  removing 'build'
Failed to build torch-scatter
Installing collected packages: torch-scatter
  Running setup.py install for torch-scatter: started
  Running command Running setup.py install for torch-scatter
  running install
  /opt/conda/envs/env/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/torch_scatter
  copying torch_scatter/placeholder.py -> build/lib.linux-x86_64-3.9/torch_scatter
  copying torch_scatter/segment_csr.py -> build/lib.linux-x86_64-3.9/torch_scatter
  copying torch_scatter/utils.py -> build/lib.linux-x86_64-3.9/torch_scatter
  copying torch_scatter/scatter.py -> build/lib.linux-x86_64-3.9/torch_scatter
  copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.9/torch_scatter
  copying torch_scatter/segment_coo.py -> build/lib.linux-x86_64-3.9/torch_scatter
  creating build/lib.linux-x86_64-3.9/test
  copying test/test_zero_tensors.py -> build/lib.linux-x86_64-3.9/test
  copying test/test_scatter.py -> build/lib.linux-x86_64-3.9/test
  copying test/test_broadcasting.py -> build/lib.linux-x86_64-3.9/test
  copying test/test_segment.py -> build/lib.linux-x86_64-3.9/test
  copying test/utils.py -> build/lib.linux-x86_64-3.9/test
  copying test/test_multi_gpu.py -> build/lib.linux-x86_64-3.9/test
  copying test/__init__.py -> build/lib.linux-x86_64-3.9/test
  copying test/test_gather.py -> build/lib.linux-x86_64-3.9/test
  creating build/lib.linux-x86_64-3.9/torch_scatter/composite
  copying torch_scatter/composite/std.py -> build/lib.linux-x86_64-3.9/torch_scatter/composite
  copying torch_scatter/composite/logsumexp.py -> build/lib.linux-x86_64-3.9/torch_scatter/composite
  copying torch_scatter/composite/softmax.py -> build/lib.linux-x86_64-3.9/torch_scatter/composite
  copying torch_scatter/composite/__init__.py -> build/lib.linux-x86_64-3.9/torch_scatter/composite
  running egg_info
  writing torch_scatter.egg-info/PKG-INFO
  writing dependency_links to torch_scatter.egg-info/dependency_links.txt
  writing requirements to torch_scatter.egg-info/requires.txt
  writing top-level names to torch_scatter.egg-info/top_level.txt
  reading manifest file 'torch_scatter.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/builds/cookieyong/env/pytorch_scatter/setup.py", line 97, in <module>
      setup(
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
      super().run_command(command)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
      return orig.install.run(self)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 670, in run
      self.run_command('build')
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
      super().run_command(command)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
      super().run_command(command)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/opt/conda/envs/env/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 396, in build_extensions
      self._check_abi()
    File "/opt/conda/envs/env/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 767, in _check_abi
      check_compiler_abi_compatibility(compiler)
    File "/opt/conda/envs/env/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 300, in check_compiler_abi_compatibility
      if not check_compiler_ok_for_platform(compiler):
    File "/opt/conda/envs/env/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 257, in check_compiler_ok_for_platform
      which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
    File "/opt/conda/envs/env/lib/python3.9/subprocess.py", line 424, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/opt/conda/envs/env/lib/python3.9/subprocess.py", line 528, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
  error: subprocess-exited-with-error
  
  × Running setup.py install for torch-scatter did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /opt/conda/envs/env/bin/python3.9 -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize
  
  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__
  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/builds/cookieyong/env/pytorch_scatter/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' install --record /tmp/pip-record-54x5_vny/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/envs/env/include/python3.9/torch-scatter
  cwd: /builds/cookieyong/env/pytorch_scatter/
  Running setup.py install for torch-scatter: finished with status 'error'
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> torch-scatter
note: This is an issue with the package mentioned above, not pip.
```

**Comment by yongkangzhao** [comment]
I found the problem, and solution.
I was using: pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime, which I assume doesn't have all the tools to compile.
switching to: pytorch/pytorch:1.11.0-cuda11.3-cudnn8-devel
was all I needed to do.
