### ISSUE TITLE
[scatter_min] RuntimeError: Not compiled with CUDA support

### ISSUE THREAD

**Issue by colinpeng-datascience** [rusty1s/pytorch_scatter#312]
Dear authors, 

Hi! I am new to torch_scatter and encountered the same problem as #271. I would be grateful to any help. 

The error message I got:
```
>python3 run/test_scatter.py
Traceback (most recent call last):
  File "run/test_scatter.py", line 10, in <module>
    out, argmin = scatter_min(src, index)
  File "/opt/conda/lib/python3.7/site-packages/torch_scatter/scatter.py", line 65, in scatter_min
    return torch.ops.torch_scatter.scatter_min(src, index, dim, out, dim_size)
RuntimeError: Not compiled with CUDA support
```

The image I am using: `nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04`

The commands I used to install the related packages (I use conda, python version 3.7.4):
```
pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html;
conda install -y -c conda-forge pycuda;
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.8.1+cu111.html;
```

The code that produces this error (test_scatter.py):
```
import torch
from torch_scatter import scatter_min

src = torch.Tensor([[-2, 0, -1, -4, -3], [0, -2, -1, -3, -4]])
src = src.cuda()
index = torch.tensor([[ 4, 5,  4,  2,  3], [0,  0,  2,  2,  1]])
index = index.cuda()

out, argmin = scatter_min(src, index)
```

Thanks in advance for any help.

**Comment by rusty1s** [comment]
```
pip install torch-scatter==2.0.8 -f https://data.pyg.org/whl/torch-1.8.1+cu111.html
```
should resolve this.

**Comment by colinpeng-datascience** [comment]
@rusty1s  It worked! Thank you very much! Saved my day.

**Comment by gkirgizov** [comment]
For anyone else stumbling there, here's more info: https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html#additional-libraries
