### ISSUE TITLE
Undefined _spmm_cpu.so error message on Ubuntu 22

### ISSUE THREAD

**Issue by ivan-marroquin** [rusty1s/pytorch_scatter#329]
Hi,

Many thanks for making available this great package!

I have Python 3.9.0 on Ubuntu 22 with pytorch 1.12.1 and Cuda 11.5.

I installed PyG with this command:
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.11.0+cu115.html

When I ran the command: "from torch_geometric.data import Data", I get the following error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ivan/python_3.9.0/lib/python3.9/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/ivan/python_3.9.0/lib/python3.9/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/ivan/python_3.9.0/lib/python3.9/site-packages/torch_geometric/data/data.py", line 20, in <module>
    from torch_sparse import SparseTensor
  File "/home/ivan/python_3.9.0/lib/python3.9/site-packages/torch_sparse/__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/ivan/python_3.9.0/lib/python3.9/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/home/ivan/python_3.9.0/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/ivan/python_3.9.0/lib/python3.9/site-packages/torch_sparse/_spmm_cpu.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE

Then, I tried the following:
- Uninstall torch-scatter and torch-sparser
- Install only torch-scatter using command outlined above
- Install only torch-sparser using command outline above

Unfortunately, I stil got the same issue.

Any suggestions?

Best regards,
Ivan

**Comment by ivan-marroquin** [comment]
Hi,

I think that I was able to solve the issue by following these installation steps:
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
pip3 install torch-sparse -f https://data.pyg.org/whl/torch-1.12.1+cu113.html
pip3 install torch-scatter -f https://data.pyg.org/whl/torch-1.12.1+cu113.html
pip3 install torch-cluster -f https://data.pyg.org/whl/torch-1.12.1+cu113.html

According to stackflow answers that I found. With cuda 11.5 installed on Ubuntu, we can still use pytorch for cuda 11.3

Hope this helps,
Ivan
