### ISSUE TITLE
OSError with pytorch1.12.1 + cuda11.6

### ISSUE THREAD

**Issue by BL-Lac149597870** [rusty1s/pytorch_scatter#333]
Hi~
I have encountered the following problem using **pytorch1.12.1 + cuda11.6 + pytorch-scatter2.0.9**

> Traceback (most recent call last):
  File "/home/qianhao/.conda/envs/diffsbdd/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/qianhao/.conda/envs/diffsbdd/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/qianhao/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/qianhao/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/qianhao/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/qianhao/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/qianhao/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/qianhao/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/qianhao/DiffSBDD/train.py", line 11, in <module>
    from lightning_modules import LigandPocketDDPM
  File "/home/qianhao/DiffSBDD/lightning_modules.py", line 15, in <module>
    from torch_scatter import scatter_add, scatter_mean
  File "/home/qianhao/.conda/envs/diffsbdd/lib/python3.9/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/qianhao/.local/lib/python3.9/site-packages/torch/_ops.py", line 220, in load_library
    ctypes.CDLL(path)
  File "/home/qianhao/.conda/envs/diffsbdd/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/qianhao/.conda/envs/diffsbdd/lib/python3.9/site-packages/torch_scatter/_scatter_cuda.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb

Any ideas?

**Comment by rusty1s** [comment]
This usually suggests that there was a version mismatch. What's the output of `torch.__version__` and `nvcc --version`?

**Comment by BL-Lac149597870** [comment]
@rusty1s Thanks for replying~ I have successfully installed pytorch_scatter with cuda11.3.
