### ISSUE TITLE
RuntimeError: Some elements marked as dirty during the forward method were not returned as output. The inputs that are modified inplace must all be outputs of the Function.

### ISSUE THREAD

**Issue by Nightwatch-Fox11** [rusty1s/pytorch_scatter#335]
Hello, thanks for this great work!
I'm working on my deep learning model with `scatter` from `torch_scatter`. Specifically, I use `dst = scatter(src, dst_idx_tmp, dim=-2, out=dst, reduce='max')` in every ViT encoder block, I'm sure the input shape is correct. However, it’s strange that, when I train my model and debug this line, it seems that this line runs twice. After the twice run, it shows the following error:
```
Traceback (most recent call last):
  File "/data/new/SOT/OSTrack_new/lib/train/../../lib/train/trainers/base_trainer.py", line 85, in train
    self.train_epoch()
  File "/data/new/SOT/OSTrack_new/lib/train/../../lib/train/trainers/ltr_trainer.py", line 133, in train_epoch
    self.cycle_dataset(loader)
  File "/data/new/SOT/OSTrack_new/lib/train/../../lib/train/trainers/ltr_trainer.py", line 86, in cycle_dataset
    loss, stats = self.actor(data)
  File "/data/new/SOT/OSTrack_new/lib/train/../../lib/train/actors/ostrack.py", line 31, in __call__
    out_dict = self.forward_pass(data)
  File "/data/new/SOT/OSTrack_new/lib/train/../../lib/train/actors/ostrack.py", line 73, in forward_pass
    return_last_attn=False)
  File "/opt/conda/envs/lwh/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/new/SOT/OSTrack_new/lib/train/../../lib/models/ostrack/ostrack.py", line 50, in forward
    return_last_attn=return_last_attn, )
  File "/opt/conda/envs/lwh/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/new/SOT/OSTrack_new/lib/train/../../lib/models/ostrack/base_backbone.py", line 154, in forward
    x, aux_dict = self.forward_features(z, x,)
  File "/data/new/SOT/OSTrack_new/lib/train/../../lib/models/ostrack/vit_tome.py", line 85, in forward_features
    x, source, size = blk(x, global_index_t, source_=source, size_=size)
  File "/opt/conda/envs/lwh/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/new/SOT/OSTrack_new/lib/train/../../lib/models/layers/attn_blocks.py", line 175, in forward
    merge, x_s, source_
  File "/data/new/SOT/OSTrack_new/lib/train/../../lib/models/ostrack/tome/merge.py", line 251, in merge_source
    source = merge(source, mode="amax")
  File "/data/new/SOT/OSTrack_new/lib/train/../../lib/models/ostrack/tome/merge.py", line 84, in merge
    dst = scatter(src, dst_idx_tmp, dim=-2, out=dst, reduce='max')
  File "/opt/conda/envs/lwh/lib/python3.7/site-packages/torch_scatter/scatter.py", line 160, in scatter
    return scatter_max(src, index, dim, out, dim_size)[0]
  File "/opt/conda/envs/lwh/lib/python3.7/site-packages/torch_scatter/scatter.py", line 72, in scatter_max
    return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
RuntimeError: Some elements marked as dirty during the forward method were not returned as output. The inputs that are modified inplace must all be outputs of the Function.
```
My development environment is `PyTorch 1.10.1-cuda11.3 + python3.7` and my `torch-scatter` version is 2.0.9. This problem really confused me, I’m wondering if anyone could help me with this？

**Comment by Nightwatch-Fox11** [comment]
Actually, the original command is `dst = dst.scatter_reduce(-2, dst_idx.expand(n, r, c), src, reduce=mode)`. However, this command needs `PyTorch >= 1.12.0` because of the `torch.Tensor.scatter_reduce` function, and for some reason I can't use `PyTorch >=1.12.0` though it works well when running this line, so I replace this command with `dst = scatter(src, dst_idx_tmp, dim=-2, out=dst, reduce='max')` to run the code in `PyTorch 1.10.1`. So I'm wondering why this command shows the above error.

**Comment by rusty1s** [comment]
Mh, are you sure `dst.scatter_reduce` works? What's the output of `print.requires_grad` before running the `scatter_reduce` call? Can you try to run `scatter(src, dst_idx_tmp, dim=-2, out=dst.clone(), reduce='max')`?

**Comment by Nightwatch-Fox11** [comment]
Thanks for your reply, I'm very sure that `dst.scatter_reduce` works in `PyTorch 1.12.0`, and the output of `print(dst.requires_grad)` is always `False`. I've just tried `scatter(src, dst_idx_tmp, dim=-2, out=dst.clone(), reduce='max')`, it works! No error reported, this is really amazing!
