### ISSUE TITLE
undefined symbol _ZN5torch3jit17parseSchemaOrNameERKSs

### ISSUE THREAD

**Issue by william0620** [rusty1s/pytorch_scatter#348]
When I run my DL code using scatter, it errors:
`
bash dev_scripts/w_n360/chair_test.sh
Traceback (most recent call last):

  File "/root/miniconda3/envs/nerf/lib/python3.10/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/root/miniconda3/envs/nerf/lib/python3.10/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/root/miniconda3/envs/nerf/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /root/miniconda3/envs/nerf/lib/python3.10/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
`
My system is 1.8.1+Cuda 11.7 and my NVCC version is 11.1
I don't know what's the reason. Thanks!

Best Regards

**Comment by rusty1s** [comment]
Yeah, what is the CUDA version installed by PyTorch?
```
python -c "import torch; print(torch.version.cuda)"
```
Can you try to install from https://data.pyg.org/whl/torch-1.8.1%2Bcu111.html? Since only older versions are provided, you need to specify the version
```
pip install torch-scatter==2.0.8 -f https://data.pyg.org/whl/torch-1.8.1+cu111.html

**Comment by william0620** [comment]
Hi, CUDA version installed by PyTorch is 11.1. Thanks for your kind reply, I used your command provided and solved the eroor above; However, when I tried to run my program agian, it errors:`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/pointnerf/run/train_ft.py", line 13, in <module>
    from models.mvs.mvs_points_model import MvsPointsModel
  File "/root/pointnerf/run/../models/mvs/mvs_points_model.py", line 6, in <module>
    from .models import *
  File "/root/pointnerf/run/../models/mvs/models.py", line 4, in <module>
    from .mvs_utils import *
  File "/root/pointnerf/run/../models/mvs/mvs_utils.py", line 4, in <module>
    from torch_scatter import scatter_min, segment_coo, scatter_mean
  File "/root/miniconda3/envs/nerf/lib/python3.10/site-packages/torch_scatter/__init__.py", line 17, in <module>
    raise AttributeError(e)
AttributeError: 'NoneType' object has no attribute 'origin'
Traceback (most recent call last):
  File "/root/miniconda3/envs/nerf/lib/python3.10/site-packages/torch_scatter/__init__.py", line 14, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
AttributeError: 'NoneType' object has no attribute 'origin'`

Thanks!

**Comment by rusty1s** [comment]
I don't think PyTorch 1.8 supports CUDA 11.7 - how is this possible? :) The `NoneType` object error indicates that CUDA extension binaries are not found, which suggests that you are still doing manual compiliation. What happens if you uninstall `torch-scatter` repeatedly, and then run
```
pip install --no-index torch-scatter==2.0.8 -f https://data.pyg.org/whl/torch-1.8.1+cu111.html

**Comment by william0620** [comment]
Hi @rusty1s , I don't know why my base env cuda version is 11.1 and when I tired to create a new env, it's cuda is 11.7.BTW, I tried to clone a env and made it a CUDA 11.1. However, it comes to the earlier OS error:
`Traceback (most recent call last):
  File "test_ft.py", line 13, in <module>
    from models.mvs.mvs_points_model import MvsPointsModel
  File "/root/pointnerf/run/../models/mvs/mvs_points_model.py", line 6, in <module>
    from .models import *
  File "/root/pointnerf/run/../models/mvs/models.py", line 4, in <module>
    from .mvs_utils import *
  File "/root/pointnerf/run/../models/mvs/mvs_utils.py", line 4, in <module>
    from torch_scatter import scatter_min, segment_coo, scatter_mean
  File "/root/miniconda3/lib/python3.8/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/root/miniconda3/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /root/miniconda3/lib/python3.8/site-packages/torch_scatter/_scatter_cuda.so: undefined symbol: _ZNK2at6Tensor6deviceEv`
Thank again for your reply!

**Comment by rusty1s** [comment]
Can you share some system information on your end? What is `nvcc --version` and what does `torch.version.cuda` return? One problem I see is that the extension modules will be loaded in via CUDA 11.7 (your system CUDA) while PyTorch expects an earlier CUDA version. The most easiest approach would probably be to just upgrade your PyTorch version. If you cannot do that, you may want to link your CUDA installation coming from PyTorch to `LD_LIBRARY_PATH`.
```
export LD_LIBRARY_PATH=/root/miniconda3/lib:$LD_LIBRARY_PATH

**Comment by william0620** [comment]
For the env I'm using now, the nvcc version is cuda 11.1.105, and torch.version.cuda is 11.1 too. However, the nvidia-smi reads CUDA version is 11.7.
I just tried to enter `export LD_LIBRARY_PATH=/root/miniconda3/lib:$LD_LIBRARY_PATH`, and it did not work. I'm using the online GPU, so it's not convenient to upgrade, I need to upgrade the whole mirror. I'm now trying to change to pytorch 1.11.0. Thanks!

**Comment by william0620** [comment]
Thanks, I manage to solve the problems!

**Comment by rusty1s** [comment]
Super! Please share how you solved it :)

**Comment by william0620** [comment]
I just updated my pytorch version from 1.8.1 to 1.11, and remains cuda version with 11.1, while nvidia-smi(system?) still being 11.7.
Thanks a lot, U're really a nice developer.^^
