### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by nihalgupta84** [rusty1s/pytorch_scatter#371]
i have torch 1.11.0 and cuda 11.0
and installed torch-scatter using 

pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.11.0+cu111.html

but getting the mismatch error

(ptlflow) anil@anil-gpu2:/media/anil/New Volume1/Nihal/ptlflow$ CUDA_VISIBLE_DEVICES=0 python3 train.py csflow --logger --enable_checkpointing --gpus 1 --log_every_n_steps 1000 --enable_progress_bar True --max_steps 120000 --train_batch_size 6  --train_dataset chairs-train --val_dataset chairs-val --accelerator gpu --resume_from_checkpoint "ptlflow_logs/csflow-chairs/lightning_logs/version_0/checkpoints/csflow_train_epoch=8_step=50022.ckpt"
Traceback (most recent call last):
  File "train.py", line 29, in <module>
    from ptlflow import get_model, get_model_reference
  File "/media/anil/New Volume1/Nihal/ptlflow/ptlflow/__init__.py", line 63, in <module>
    from ptlflow.models.scv.scv import SCVEighth, SCVQuarter
  File "/media/anil/New Volume1/Nihal/ptlflow/ptlflow/models/scv/scv.py", line 9, in <module>
    from .utils import bilinear_sampler, coords_grid, coords_grid_y_first,\
  File "/media/anil/New Volume1/Nihal/ptlflow/ptlflow/models/scv/utils.py", line 6, in <module>
    from torch_scatter import scatter_softmax, scatter_add
  File "/home/anil/miniconda3/envs/ptlflow/lib/python3.8/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/anil/miniconda3/envs/ptlflow/lib/python3.8/site-packages/torch/_ops.py", line 220, in load_library
    ctypes.CDLL(path)
  File "/home/anil/miniconda3/envs/ptlflow/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/anil/miniconda3/envs/ptlflow/lib/python3.8/site-packages/torch_scatter/_scatter_cuda.so: undefined symbol: _ZN3c1012OptionalType3getENS_4Type24SingletonOrSharedTypePtrIS1_EE

**Comment by rusty1s** [comment]
Can you try to uninstall via
```
pip uninstall torch-scatter
pip install torch-scatter==2.0.9 -f https://pytorch-geometric.com/whl/torch-1.11.0+cu111.html
