### ISSUE TITLE
Module import error

### ISSUE THREAD

**Issue by zhoushengisnoob** [rusty1s/pytorch_scatter#38]
## log
File "/home/zhousheng/.local/lib/python3.6/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home/zhousheng/.local/lib/python3.6/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home/zhousheng/.local/lib/python3.6/site-packages/torch_scatter/utils/ext.py", line 5, in <module>
    import torch_scatter.scatter_cuda
ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda'

## Environment
OS: ubuntu 16.04
python: 3.6.7
pytorch:1.0.0

**Comment by rusty1s** [comment]
Can you follow [the installation guide](https://rusty1s.github.io/pytorch_geometric/build/html/notes/installation.html) and report the actual installation error?

**Comment by zhoushengisnoob** [comment]
The installation of torch-scatter is success, the error occurs when calling scatter in torch-geometric, the full error information is:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from capsgnn import CapsGNNTrainer
  File "/home/zhousheng/CapsGNN/src/capsgnn.py", line 8, in <module>
    from torch_geometric.nn import GCNConv
  File "/home/zhousheng/.local/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/zhousheng/.local/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 4, in <module>
    from torch_geometric.data import Batch
  File "/home/zhousheng/.local/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/zhousheng/.local/lib/python3.6/site-packages/torch_geometric/data/data.py", line 4, in <module>
    from torch_geometric.utils import (contains_isolated_nodes,
  File "/home/zhousheng/.local/lib/python3.6/site-packages/torch_geometric/utils/__init__.py", line 2, in <module>
    from .scatter import scatter_
  File "/home/zhousheng/.local/lib/python3.6/site-packages/torch_geometric/utils/scatter.py", line 1, in <module>
    import torch_scatter
  File "/home/zhousheng/.local/lib/python3.6/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home/zhousheng/.local/lib/python3.6/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home/zhousheng/.local/lib/python3.6/site-packages/torch_scatter/utils/ext.py", line 5, in <module>
    import torch_scatter.scatter_cuda
ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda'

Thanks

**Comment by rusty1s** [comment]
No, the installation did not succeed, otherwise it would find `scatter_cuda`. Your CUDA setup seems to be incomplete.

**Comment by jlevy44** [comment]
I've been sending my jobs to be run on PBS Torque.

Sometimes am running with GPU sometimes without. Is there flexibility in the install to account for not running on GPU if installing when torch.cuda.is_available()?

**Comment by rusty1s** [comment]
You could check how to make `CUDA_HOME=None` (see [here](https://github.com/rusty1s/pytorch_scatter/blob/master/setup.py#L17)), which seems to require removing cuda stuff from the path (see [here](https://github.com/pytorch/pytorch/blob/3bfdffe4870dda10e8b99a77cd6e0b034adbcd2b/torch/utils/cpp_extension.py#L24-L50)).
