### ISSUE TITLE
Failing to install torch-scatter using pip m2 max apple chip

### ISSUE THREAD

**Issue by NripeshN** [rusty1s/pytorch_scatter#386]
I get the following error when running `pip install torch-scatter`

```
Collecting torch-scatter
  Using cached torch_scatter-2.1.1.tar.gz (107 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/j_/nbyvxq0j7hl4t1t2px8t3hlm0000gn/T/pip-install-oeu_01qk/torch-scatter_d51b150e7835402bbda89242e652a0b8/setup.py", line 11, in <module>
          from torch.utils.cpp_extension import (CUDA_HOME, BuildExtension, CppExtension,
        File "/Users/nripeshniketan/Documents - Nripesh’s MacBook Pro/python_programs/ivy/ivy_dev/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 19, in <module>
          from .hipify import hipify_python
        File "/Users/nripeshniketan/Documents - Nripesh’s MacBook Pro/python_programs/ivy/ivy_dev/lib/python3.11/site-packages/torch/utils/hipify/hipify_python.py", line 34, in <module>
          from .cuda_to_hip_mappings import CUDA_TO_HIP_MAPPINGS
        File "/Users/nripeshniketan/Documents - Nripesh’s MacBook Pro/python_programs/ivy/ivy_dev/lib/python3.11/site-packages/torch/utils/hipify/cuda_to_hip_mappings.py", line 34, in <module>
          rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      NotADirectoryError: [Errno 20] Not a directory: 'hipconfig'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by rusty1s** [comment]
Thanks for letting us know. Are you trying to install this on AMD GPUs?

**Comment by NripeshN** [comment]
No i am trying to install this on the apple silicon chip

**Comment by rusty1s** [comment]
This looks related: https://github.com/pytorch/pytorch/issues/98629
