### ISSUE TITLE
Issue installing pytorch scatter - Having rust is now a requirement

### ISSUE THREAD

**Issue by FMelloMascarenhas-Cohere** [rusty1s/pytorch_scatter#387]
Hi, installing pytorch scatter in macos wanst an issue for me before. But now I am getting the error below. If I do `brew install rust`, it installs well, but having this requirement seems a bit odd

```
Building wheels for collected packages: safetensors
  Building wheel for safetensors (pyproject.toml) ... error: subprocess-exited-with-error
  
  × Building wheel for safetensors (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-cpython-38
      creating build/lib.macosx-10.9-x86_64-cpython-38/safetensors
      copying py_src/safetensors/paddle.py -> build/lib.macosx-10.9-x86_64-cpython-38/safetensors
      copying py_src/safetensors/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-38/safetensors
      copying py_src/safetensors/numpy.py -> build/lib.macosx-10.9-x86_64-cpython-38/safetensors
      copying py_src/safetensors/tensorflow.py -> build/lib.macosx-10.9-x86_64-cpython-38/safetensors
      copying py_src/safetensors/torch.py -> build/lib.macosx-10.9-x86_64-cpython-38/safetensors
      copying py_src/safetensors/flax.py -> build/lib.macosx-10.9-x86_64-cpython-38/safetensors
      running build_ext
      running build_rust
      error: can't find Rust compiler
      
      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
      
      To update pip, run:
      
          pip install --upgrade pip
      
      and then retry package installation.
      
      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs/) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for safetensors
Failed to build safetensors
ERROR: Could not build wheels for safetensors, which is required to install pyproject.toml-based projects
```

**Comment by FMelloMascarenhas-Cohere** [comment]
using pip install torch-scatter -f https://data.pyg.org/whl/torch-2.0.0+${CUDA}.html works well

**Comment by mumdark** [comment]
> using pip install torch-scatter -f [https://data.pyg.org/whl/torch-2.0.0+${CUDA}.html](https://data.pyg.org/whl/torch-2.0.0+$%7BCUDA%7D.html) works well


I am trying to install using the following code, but it does not work:
```py
pip install torch==1.11.0+cu115 torchvision==0.12.0+cu115 torchaudio==0.11.0 -f https://download.pytorch.org/whl/torch_stable.html

pip install torch-scatter -f https://data.pyg.org/whl/torch-1.11.0+cu115.html
```

```py
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Looking in links: https://data.pyg.org/whl/torch-1.11.0+cu115.html
Collecting torch-scatter
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f5/ab/2a44ecac0f891dd0d765fc59ac8d277c6283a31907626560e72685df2ed6/torch_scatter-2.1.2.tar.gz (108 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: torch-scatter
  Building wheel for torch-scatter (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/torch_scatter
      copying torch_scatter/segment_coo.py -> build/lib.linux-x86_64-cpython-39/torch_scatter
      copying torch_scatter/placeholder.py -> build/lib.linux-x86_64-cpython-39/torch_scatter
      copying torch_scatter/segment_csr.py -> build/lib.linux-x86_64-cpython-39/torch_scatter
      copying torch_scatter/__init__.py -> build/lib.linux-x86_64-cpython-39/torch_scatter
      copying torch_scatter/testing.py -> build/lib.linux-x86_64-cpython-39/torch_scatter
      copying torch_scatter/scatter.py -> build/lib.linux-x86_64-cpython-39/torch_scatter
      copying torch_scatter/utils.py -> build/lib.linux-x86_64-cpython-39/torch_scatter
      creating build/lib.linux-x86_64-cpython-39/torch_scatter/composite
      copying torch_scatter/composite/std.py -> build/lib.linux-x86_64-cpython-39/torch_scatter/composite
      copying torch_scatter/composite/logsumexp.py -> build/lib.linux-x86_64-cpython-39/torch_scatter/composite
      copying torch_scatter/composite/__init__.py -> build/lib.linux-x86_64-cpython-39/torch_scatter/composite
      copying torch_scatter/composite/softmax.py -> build/lib.linux-x86_64-cpython-39/torch_scatter/composite
      running egg_info
      writing torch_scatter.egg-info/PKG-INFO
      writing dependency_links to torch_scatter.egg-info/dependency_links.txt
      writing requirements to torch_scatter.egg-info/requires.txt
      writing top-level names to torch_scatter.egg-info/top_level.txt
      reading manifest file 'torch_scatter.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*' found under directory 'test'
      adding license file 'LICENSE'
      writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-2mrj5izk/torch-scatter_893f36fdb9fd4ea2b08d318b6f325979/setup.py", line 120, in <module>
          setup(
        File "/mnt/data5/liudefu/conda/envs/python39/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/mnt/data5/liudefu/conda/envs/python39/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/mnt/data5/liudefu/conda/envs/python39/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/mnt/data5/liudefu/conda/envs/python39/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/mnt/data5/liudefu/conda/envs/python39/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/mnt/data5/liudefu/conda/envs/python39/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/mnt/data5/liudefu/conda/envs/python39/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/mnt/data5/liudefu/conda/envs/python39/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/mnt/data5/liudefu/conda/envs/python39/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/mnt/data5/liudefu/conda/envs/python39/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/mnt/data5/liudefu/conda/envs/python39/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/mnt/data5/liudefu/conda/envs/python39/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/mnt/data5/liudefu/conda/envs/python39/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/mnt/data5/liudefu/conda/envs/python39/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/mnt/data5/liudefu/conda/envs/python39/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/mnt/data5/liudefu/conda/envs/python39/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/mnt/data5/liudefu/conda/envs/python39/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 410, in build_extensions
          self._check_cuda_version()
        File "/mnt/data5/liudefu/conda/envs/python39/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 787, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (9.1) mismatches the version that was used to compile
      PyTorch (11.5). Please make sure to use the same CUDA versions.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torch-scatter
  Running setup.py clean for torch-scatter
Failed to build torch-scatter
ERROR: Could not build wheels for torch-scatter, which is required to install pyproject.toml-based projects

```

**Comment by rusty1s** [comment]
Try
```
pip install torch-scatter==2.0.9 -f https://data.pyg.org/whl/torch-1.11.0+cu115.html

**Comment by mumdark** [comment]
> Try
> 
> ```
> pip install torch-scatter==2.0.9 -f https://data.pyg.org/whl/torch-1.11.0+cu115.html
> ```

Thanks! It worked.
