### ISSUE TITLE
torch_spline_conv/_basis_cuda.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv

### ISSUE THREAD

**Issue by arunraja-hub** [rusty1s/pytorch_scatter#397]
```
Traceback (most recent call last):
  File "/PS-VAE/src/train.py", line 11, in <module>
    from pl_models import PSVAEModel
  File "PS-VAE/src/pl_models/__init__.py", line 6, in <module>
    from .ps_vae_model import PSVAEModel
  File "/src/pl_models/ps_vae_model.py", line 11, in <module>
    from modules.encoder import Encoder
  File "//PS-VAE/src/modules/encoder.py", line 9, in <module>
    from torch_geometric.nn import GINEConv
  File "/psvae/lib/python3.8/site-packages/torch_geometric/nn/__init__.py", line 3, in <module>
    from .sequential import Sequential
  File "/lib/python3.8/site-packages/torch_geometric/nn/sequential.py", line 8, in <module>
    from torch_geometric.nn.conv.utils.jit import class_from_module_repr
  File "psvae/lib/python3.8/site-packages/torch_geometric/nn/conv/__init__.py", line 25, in <module>
    from .spline_conv import SplineConv
  File "/psvae/lib/python3.8/site-packages/torch_geometric/nn/conv/spline_conv.py", line 16, in <module>
    from torch_spline_conv import spline_basis, spline_weighting
  File "/psvae/lib/python3.8/site-packages/torch_spline_conv/__init__.py", line 11, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "/psvae/lib/python3.8/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/psvae/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /psvae/lib/python3.8/site-packages/torch_spline_conv/_basis_cuda.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv
```

I am getting this error despite having reinstalled torch, scatter, spline, sparse etc... the right way several times. My env is as follows:
```
Collecting environment information...
PyTorch version: 1.8.1+cu101
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 8.1.1911 (Core)  (x86_64)
GCC version: (GCC) 8.3.1 20190507 (Red Hat 8.3.1-4)
Clang version: Could not collect
CMake version: version 3.11.4

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: NVIDIA H100 PCIe
GPU 1: NVIDIA H100 PCIe

Nvidia driver version: 525.116.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] pytorch-lightning==1.5.7
[pip3] torch==1.8.1+cu101
[pip3] torch-cluster==1.6.0
[pip3] torch-geometric==2.1.0.post1
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.12
[pip3] torch-spline-conv==1.2.1
[pip3] torchaudio==0.8.1
[pip3] torchmetrics==0.9.3
[pip3] torchvision==0.9.1+cu101
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] cudatoolkit-dev           10.1.243             h516909a_3    conda-forge
[conda] numpy                     1.24.4                   pypi_0    pypi
[conda] pytorch-lightning         1.5.7                    pypi_0    pypi
[conda] torch                     1.8.1+cu101              pypi_0    pypi
[conda] torch-cluster             1.6.0                    pypi_0    pypi
[conda] torch-geometric           2.1.0.post1              pypi_0    pypi
[conda] torch-scatter             2.0.9                    pypi_0    pypi
[conda] torch-sparse              0.6.12                   pypi_0    pypi
[conda] torch-spline-conv         1.2.1                    pypi_0    pypi
[conda] torchaudio                0.8.1                    pypi_0    pypi
[conda] torchmetrics              0.9.3                    pypi_0    pypi
[conda] torchvision               0.9.1+cu101              pypi_0    pypi
```

@rusty1s please help

**Comment by rusty1s** [comment]
I don't see any wheel for `torch-scatter==2.09` at https://data.pyg.org/whl/torch-1.8.1%2Bcu101.html. So maybe
```
pip uninstall torch-scatter
pip install torch-scatter==2.0.8 -f https://data.pyg.org/whl/torch-1.8.1+cu101.html
```
is all that is needed.
