### ISSUE TITLE
OSError: /usr/local/lib/python3.10/dist-packages/torch_sparse/_spmm_cuda.so: undefined symbol:

### ISSUE THREAD

**Issue by Soumya-Sharma-20** [rusty1s/pytorch_scatter#400]
I tried re-installing torch_sparse version compatible with pytorch 2.1.0 and 11.8 cuda , still same issue persists
i even downgraded the cuda version to 10.2 to match the environment requirements by the Dual-DMP repository
Earlier the repositpry was working fine , this issue occured out of nowhere . 
please explain and help with the debugging

the current (default) nvcc version of my colab is 11.8 .
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab Notebooks/fb/Dual-DMP/main4real.py", line 8, in <module>
    import util.datamaker as Datamaker
  File "/content/drive/MyDrive/Colab Notebooks/fb/Dual-DMP/util/datamaker.py", line 5, in <module>
    from torch_geometric.data import Data
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/usr/local/lib/python3.10/dist-packages/torch_sparse/__init__.py", line 14, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 852, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.10/dist-packages/torch_sparse/_spmm_cuda.so: undefined symbol: _ZN5torch8autograd13_wrap_outputsERKSt6vectorIN2at6TensorESaIS3_EERKSt13unordered_setIPN3c1010TensorImplESt4hashISB_ESt8equal_toISB_ESaISB_EESJ_NS9_8ArrayRefINS9_8optionalIS3_EEEERKSt10shared_ptrINS0_4NodeEESt8functionIFS5_S5_S5_

**Comment by rusty1s** [comment]
How did you install `torch-sparse`? Are you running this on Google Colab (works fine on my end)?
