### ISSUE TITLE
An issue occurred while importing 'torch-scatter'.

### ISSUE THREAD

**Issue by BlacMountain** [rusty1s/pytorch_scatter#430]

**Comment by BlacMountain** [comment]
UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: dlopen(/Users/wuyou/PycharmProjects/MOTIFY/motif/venv/lib/python3.9/site-packages/torch_scatter/_version_cpu.so, 0x0006): Symbol not found: __ZN3c1017RegisterOperatorsD1Ev
  Referenced from: <D4CEE6C0-798A-3492-87CE-AEDC7DE216C0> /Users/wuyou/PycharmProjects/MOTIFY/motif/venv/lib/python3.9/site-packages/torch_scatter/_version_cpu.so
  Expected in:     <CFFDFEB8-056E-3D30-A1E4-4C2D7C54CFCF> /Users/wuyou/PycharmProjects/MOTIFY/motif/venv/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib

**Comment by BlacMountain** [comment]
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/PycharmProjects/models_micro.py", line 7, in <module>
    from utils import pairwise_cosine_sim, to_dense_batch, sinkhorn, rank3_diag, spectral_loss
  File "/Users/PycharmProjects/utils.py", line 15, in <module>
    from torch_scatter import scatter_add
  File "/Users/PycharmProjects/venv/lib/python3.9/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/Users/PycharmProjects/venv/lib/python3.9/site-packages/torch/_ops.py", line 1038, in load_library
    ctypes.CDLL(path)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/PycharmProjects/venv/lib/python3.9/site-packages/torch_scatter/_version_cpu.so, 0x0006): Symbol not found: __ZN3c1017RegisterOperatorsD1Ev
  Referenced from: <D4CEE6C0-798A-3492-87CE-AEDC7DE216C0> /Users/PycharmProjects/venv/lib/python3.9/site-packages/torch_scatter/_version_cpu.so
  Expected in:     <CFFDFEB8-056E-3D30-A1E4-4C2D7C54CFCF> /Users/PycharmProjects/venv/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib

**Comment by BlacMountain** [comment]
i can't fix it by changing the version of torch-scatter from 2.2.0 to 1.X.0.

**Comment by rusty1s** [comment]
Can you share more information about your PyTorch version, and what the installation log look like if you run via `pip install --verbose`?

**Comment by bybeye** [comment]
Same issue on MacOS. My PyTorch version is:

torch                      2.4.0
torch_geometric   2.5.3
torch_scatter        2.1.2

**Comment by ronyw7** [comment]
```
UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: /home/azureuser/miniconda3/envs/***/lib/python3.10/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
```

I ran into something similar and in my case, creating a new conda env with `python=3.10.12` solved the problem.

These worked fine:
```
torch 2.4.0
torch_scatter 2.1.2+pt24cu121
torch_sparse 0.6.18+pt24cu121
torch_geometric 2.6.1
ogb 1.3.6
```

**Comment by rusty1s** [comment]
How did you install PyTorch? Is PyTorch also on CUDA 12.1?

**Comment by ntw-au** [comment]
For me, this issue was caused by `conda` installing PyTorch from the `conda-forge` channel instead of the `pytorch` channel. This can be checked through `conda list`.

For me, the solution was to recreate the environment, forcing `pytorch` to install from the `pytorch` channel, e.g. `pytorch::pytorch`

e.g. (excerpt)
```
conda create --name pt23 pytorch::pytorch pytorch-cuda=12.1 pytorch-scatter -c pytorch -c nvidia -c conda-forge -c pyg 
```

**Comment by businessabstraction** [comment]
I have the same issue. Installing via pip (under conda). Using `python 3.13.2 pyg 2.6.1, torch 2.6.0+cu124`

**Comment by jtfuller3** [comment]
Switching from python 3.9 to python 3.12 fixed it for me
