### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_scatter.scatter_cpu'

### ISSUE THREAD

**Issue by AlanShaw-GitHub** [rusty1s/pytorch_scatter#44]
Hi, I have a CUDA 9.0 env, and the installation was successful(pip install --verbose --no-cache-dir  torch-scatter), but when I run python -c "import torch_scatter", the following error occurs:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home1/xiaozhenxin/pytorch_scatter/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home1/xiaozhenxin/pytorch_scatter/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home1/xiaozhenxin/pytorch_scatter/torch_scatter/utils/ext.py", line 2, in <module>
    import torch_scatter.scatter_cpu
ModuleNotFoundError: No module named 'torch_scatter.scatter_cpu'

Can I ask for what reason may cause something like this?

**Comment by rusty1s** [comment]
Hi, actually installation did not succeed. Please follow the installation guide and/or post the installation error.

**Comment by haonan3** [comment]
Hi,

I get the same error on my Mac. Did you solve this error? @AlanShaw-GitHub 
Thanks in Advance!

**Comment by port404** [comment]
could always try:

`pip3 install torch_scatter.scatter_cpu`

**Comment by rusty1s** [comment]
You should follow the installation guide [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html) and report the installation log here :)

**Comment by irondachui** [comment]
> You should follow the installation guide here and report the installation log :)

hi, i think i have successfully installed torch-scatter
```
(base) C:\Windows\system32>pip install torch-scatter
Requirement already satisfied: torch-scatter in c:\programdata\anaconda3\lib\site-packages (1.3.1)

(base) C:\Windows\system32>pip install --upgrade torch-scatter
Requirement already up-to-date: torch-scatter in c:\programdata\anaconda3\lib\site-packages (1.3.1)
```

but i still suffer the import problem
```
import torch_scatter
Traceback (most recent call last):

  File "<ipython-input-4-d3a1bea51b5c>", line 1, in <module>
    import torch_scatter

  File "C:\Users\data_with_google\gnn\GraphWaveletNeuralNetwork-master\src\torch_scatter\__init__.py", line 3, in <module>
    from .mul import scatter_mul

  File "C:\Users\data_with_google\gnn\GraphWaveletNeuralNetwork-master\src\torch_scatter\mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func

  File "C:\Users\data_with_google\gnn\GraphWaveletNeuralNetwork-master\src\torch_scatter\utils\ext.py", line 2, in <module>
    import torch_scatter.scatter_cpu

ModuleNotFoundError: No module named 'torch_scatter.scatter_cpu'
```
