### ISSUE TITLE
OSError: [WinError 127] The specified procedure could not be found with pytorch 2.2.2+cu118 + xformers 0.0.26+cu11 +ComfyUI +ZLUDA

### ISSUE THREAD

**Issue by unclemusclez** [rusty1s/pytorch_scatter#448]
mentioned in: https://github.com/rusty1s/pytorch_scatter/issues/437

i apologize if this is unsupported. 
i am trying to utilize pytorch_scatter with a ZLUDA capable build of ComfyUI
```
pytorch version: 2.2.2+cu118
xformers version: 0.0.26+cu118
```
i use:  ` pip install torch-scatter -f https://data.pyg.org/whl/torch-2.1.0+cu118.html`

and get:
![4EOZAE7](https://github.com/rusty1s/pytorch_scatter/assets/8789242/406170d5-1988-4daa-b5a4-f039f5b71cc6)
```
P:\ComfyUI-ZLUDA\custom_nodes\ComfyUI-3D-Pack\lgm\core\attention.py:22: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
Traceback (most recent call last):
  File "P:\ComfyUI-ZLUDA\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "P:\ComfyUI-ZLUDA\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 28, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\musclez\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "P:\ComfyUI-ZLUDA\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 59, in <module>
    from .algorithms.flexicubes_trainer import FlexiCubesTrainer
  File "P:\ComfyUI-ZLUDA\custom_nodes\ComfyUI-3D-Pack\algorithms\flexicubes_trainer.py", line 15, in <module>
    from ..flexicubes.loss import sdf_reg_loss
  File "P:\ComfyUI-ZLUDA\custom_nodes\ComfyUI-3D-Pack\flexicubes\loss.py", line 9, in <module>
    import torch_scatter
  File "P:\ComfyUI-ZLUDA\.venv\Lib\site-packages\torch_scatter\__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "P:\ComfyUI-ZLUDA\.venv\Lib\site-packages\torch\_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "C:\Users\musclez\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 127] The specified procedure could not be found
```

**Comment by unclemusclez** [comment]
`pip install torch-scatter -f https://data.pyg.org/whl/torch-2.2.2+cu118.html`

per: `https://pypi.org/project/torch-scatter/` installation details
make sure `${CUDA}` =  your `torch `version, ie `torch-2.2.2+cu118`
