### ISSUE TITLE
cannot install in Ubuntu

### ISSUE THREAD

**Issue by sunxiangguo** [rusty1s/pytorch_scatter#47]
(pyTorch) sxg@wow-Super-Server:/mntc/sxg/myenv/pyTorch/bin$ pip3 install torch-scatter
Collecting torch-scatter
  Using cached https://files.pythonhosted.org/packages/07/c0/f7ac424496f4a3bcb31aa993fba29077a6d42fc2624c66e90b58a566a98e/torch_scatter-1.2.0.tar.gz
Building wheels for collected packages: torch-scatter
  Building wheel for torch-scatter (setup.py) ... error
  ERROR: Complete output from command /mntc/sxg/myenv/pyTorch/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/mntc/sxg/myenv/pyTorch/bin/pip-install-j1fy_xnx/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /mntc/sxg/myenv/pyTorch/bin/pip-wheel-cfp3jqyj --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/max.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/add.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/mul.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/mean.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/div.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/min.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/sub.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/std.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter
  creating build/lib.linux-x86_64-3.6/test
  copying test/test_forward.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_multi_gpu.py -> build/lib.linux-x86_64-3.6/test
  copying test/utils.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_std.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_backward.py -> build/lib.linux-x86_64-3.6/test
  copying test/__init__.py -> build/lib.linux-x86_64-3.6/test
  creating build/lib.linux-x86_64-3.6/torch_scatter/utils
  copying torch_scatter/utils/ext.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
  copying torch_scatter/utils/gen.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
  copying torch_scatter/utils/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/mntc/sxg/myenv/pyTorch/bin/pip-install-j1fy_xnx/torch-scatter/setup.py", line 44, in <module>
      packages=find_packages(),
    File "/mntc/sxg/myenv/pyTorch/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/mntc/sxg/myenv/pyTorch/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/mntc/sxg/myenv/pyTorch/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
      _build_ext.run(self)
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/mntc/sxg/myenv/pyTorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 232, in build_extensions
      self._check_abi()
    File "/mntc/sxg/myenv/pyTorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 370, in _check_abi
      check_compiler_abi_compatibility(compiler)
    File "/mntc/sxg/myenv/pyTorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 162, in check_compiler_abi_compatibility
      if not check_compiler_ok_for_platform(compiler):
    File "/mntc/sxg/myenv/pyTorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 138, in check_compiler_ok_for_platform
      which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
    File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.6/subprocess.py", line 418, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['which', 'x86_64-linux-gnu-g++']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for torch-scatter
  Running setup.py clean for torch-scatter
Failed to build torch-scatter
Installing collected packages: torch-scatter
  Running setup.py install for torch-scatter ... error
    ERROR: Complete output from command /mntc/sxg/myenv/pyTorch/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/mntc/sxg/myenv/pyTorch/bin/pip-install-j1fy_xnx/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /mntc/sxg/myenv/pyTorch/bin/pip-record-0h8f8cv8/install-record.txt --single-version-externally-managed --compile --install-headers /mntc/sxg/myenv/pyTorch/include/site/python3.6/torch-scatter:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/max.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/add.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/mul.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/mean.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/div.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/min.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/sub.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/std.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter
    creating build/lib.linux-x86_64-3.6/test
    copying test/test_forward.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_multi_gpu.py -> build/lib.linux-x86_64-3.6/test
    copying test/utils.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_std.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_backward.py -> build/lib.linux-x86_64-3.6/test
    copying test/__init__.py -> build/lib.linux-x86_64-3.6/test
    creating build/lib.linux-x86_64-3.6/torch_scatter/utils
    copying torch_scatter/utils/ext.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
    copying torch_scatter/utils/gen.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
    copying torch_scatter/utils/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mntc/sxg/myenv/pyTorch/bin/pip-install-j1fy_xnx/torch-scatter/setup.py", line 44, in <module>
        packages=find_packages(),
      File "/mntc/sxg/myenv/pyTorch/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/mntc/sxg/myenv/pyTorch/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/mntc/sxg/myenv/pyTorch/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/mntc/sxg/myenv/pyTorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 232, in build_extensions
        self._check_abi()
      File "/mntc/sxg/myenv/pyTorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 370, in _check_abi
        check_compiler_abi_compatibility(compiler)
      File "/mntc/sxg/myenv/pyTorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 162, in check_compiler_abi_compatibility
        if not check_compiler_ok_for_platform(compiler):
      File "/mntc/sxg/myenv/pyTorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 138, in check_compiler_ok_for_platform
        which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
      File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['which', 'x86_64-linux-gnu-g++']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command "/mntc/sxg/myenv/pyTorch/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/mntc/sxg/myenv/pyTorch/bin/pip-install-j1fy_xnx/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /mntc/sxg/myenv/pyTorch/bin/pip-record-0h8f8cv8/install-record.txt --single-version-externally-managed --compile --install-headers /mntc/sxg/myenv/pyTorch/include/site/python3.6/torch-scatter" failed with error code 1 in /mntc/sxg/myenv/pyTorch/bin/pip-install-j1fy_xnx/torch-scatter/

**Comment by rusty1s** [comment]
It seems like it cannot find your compiler. Please install the Ubuntu developer tools.

**Comment by sunxiangguo** [comment]
I sovled the problem! Thanks! Here is my step, hope could help others!
Step1: make sure your gcc and g++ are under 6

sudo apt-get update
sudo apt-get install gcc-5 g++-5
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5

Step2 install build-essential:

sudo apt-get install aptitude
sudo aptitude install build-essential

Step3: install torch-scatter!
pip3 install --verbose --no-cache-dir torch-scatter

**Comment by rusty1s** [comment]
Awesome :)
