### ISSUE TITLE
UnicodeDecodeError during installation

### ISSUE THREAD

**Issue by jinze1994** [rusty1s/pytorch_scatter#58]
Please help me to install the package, thank you very much.

Problem:
```
(torch110) baijin@pku:~$ pip install torch_scatter-1.3.1.tar.gz
Processing ./torch_scatter-1.3.1.tar.gz
Building wheels for collected packages: torch-scatter
  Running setup.py bdist_wheel for torch-scatter ... error
  Failed building wheel for torch-scatter
  Running setup.py clean for torch-scatter
Failed to build torch-scatter
Installing collected packages: torch-scatter
  Running setup.py install for torch-scatter ... error
Exception:
Traceback (most recent call last):
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/compat/__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 42: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/utils/__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "/home/baijin/Lib/anaconda3/envs/torch110/lib/python3.6/site-packages/pip/compat/__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 42: invalid start byte
You are using pip version 9.0.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

My Env:
```
(torch110) baijin@pku:~/Code/test$ python collect_env.py
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.3
[conda] blas                      1.0                         mkl    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
[conda] mkl                       2018.0.3                      1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
[conda] pytorch                   1.1.0           py3.6_cuda10.0.130_cudnn7.5.1_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchvision               0.3.0           py36_cu10.0.130_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
(torch110) baijin@pku:~/Code/test$ echo $PATH
/home/baijin/Lib/anaconda3/envs/torch110/bin:/home/baijin/Lib/anaconda3/bin:/home/baijin/Lib/cuda-10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
(torch110) baijin@pku:~/Code/test$ echo $CPATH
/home/baijin/Lib/cuda-10.0/include:/home/baijin/Lib/cuda-10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
(torch110) baijin@pku:~/Code/test$ echo $LD_LIBRARY_PATH
/home/baijin/Lib/cuda-10.0/lib64:/home/baijin/Lib/cuda-10.0/extras/CUPTI/lib64:
(torch110) baijin@pku:~/Code/test$ conda list -n torch110
# packages in environment at /home/baijin/Lib/anaconda3/envs/torch110:
#
blas                      1.0                         mkl    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
certifi                   2016.2.28                py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
cffi                      1.10.0                   py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
cudatoolkit               10.0.130                      0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
freetype                  2.5.5                         2    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
intel-openmp              2019.4                      243    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
jbig                      2.1                           0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
jpeg                      9b                            0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
libffi                    3.2.1                         1    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
libpng                    1.6.30                        1    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
libtiff                   4.0.6                         3    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
mkl                       2018.0.3                      1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
ninja                     1.7.2                         0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
numpy                     1.13.3           py36ha12f23b_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
olefile                   0.44                     py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
openssl                   1.0.2l                        0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
pandas                    0.25.0                    <pip>
pillow                    4.2.1                    py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
pip                       9.0.1                    py36_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
pycparser                 2.18                     py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
python                    3.6.2                         0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
python-dateutil           2.8.0                     <pip>
pytorch                   1.1.0           py3.6_cuda10.0.130_cudnn7.5.1_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
pytz                      2019.1                    <pip>
readline                  6.2                           2    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
setuptools                36.4.0                   py36_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
six                       1.10.0                   py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
sqlite                    3.13.0                        0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
tk                        8.5.18                        0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
torchvision               0.3.0           py36_cu10.0.130_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
wheel                     0.29.0                   py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
xz                        5.2.3                         0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
zlib                      1.2.11                        0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
```

**Comment by jinze1994** [comment]
Dup of https://github.com/rusty1s/pytorch_geometric/issues/578
