### ISSUE TITLE
scatter_cpu undefined symbol: _ZN2at6detail20DynamicCUDAInterface10set_deviceE

### ISSUE THREAD

**Issue by ahyunSeo** [rusty1s/pytorch_scatter#7]
>>> import torch
>>> from torch_scatter import scatter_max
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ahyun/anaconda3/envs/py36torch040/lib/python3.6/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home/ahyun/anaconda3/envs/py36torch040/lib/python3.6/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home/ahyun/anaconda3/envs/py36torch040/lib/python3.6/site-packages/torch_scatter/utils/ext.py", line 2, in <module>
    import scatter_cpu
ImportError: /home/ahyun/anaconda3/envs/py36torch040/lib/python3.6/site-packages/scatter_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at6detail20DynamicCUDAInterface10set_deviceE

I tried install w/ both pytorch v 0.4.0 and 0.4.1, 
via pip and source and get the same error
How do I resolve this issue?

**Comment by rusty1s** [comment]
Related to https://github.com/rusty1s/pytorch_geometric/issues/18.

**Comment by kwohlfahrt** [comment]
I had this problem on Linux (Travis-CI actually) today, and it was solved by clearing the pip cache. Just leaving a note here on the off chance somebody else runs into this issue.

**Comment by seanie12** [comment]
@kwohlfahrt  can you tell me how to clear pip cache in linux ubuntu?

**Comment by qianwenyuan** [comment]
> @kwohlfahrt can you tell me how to clear pip cache in linux ubuntu?
rm -r ~/.cache/pip/
i just deleted pip cache, and reinstall torch_scatter. The problem was solved.

**Comment by w4nderlust** [comment]
I'm having the same problem on ubuntu 18.04, clearing the cache doesn;t seem to help:
```
...
    import torch_geometric.transforms as T
  File "/home/piero/dev/meta-graph/mgvenv/lib/python3.6/site-packages/torch_geometric/transforms/__init__.py", line 8, in <module>
    from .point_pair_features import PointPairFeatures
  File "/home/piero/dev/meta-graph/mgvenv/lib/python3.6/site-packages/torch_geometric/transforms/point_pair_features.py", line 2, in <module>
    from torch_geometric.nn.conv.ppf_conv import point_pair_features
  File "/home/piero/dev/meta-graph/mgvenv/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/piero/dev/meta-graph/mgvenv/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/piero/dev/meta-graph/mgvenv/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/piero/dev/meta-graph/mgvenv/lib/python3.6/site-packages/torch_geometric/data/data.py", line 4, in <module>
    from torch_geometric.utils import (contains_isolated_nodes,
  File "/home/piero/dev/meta-graph/mgvenv/lib/python3.6/site-packages/torch_geometric/utils/__init__.py", line 4, in <module>
    from .dropout import dropout_adj
  File "/home/piero/dev/meta-graph/mgvenv/lib/python3.6/site-packages/torch_geometric/utils/dropout.py", line 2, in <module>
    from torch_sparse import coalesce
  File "/home/piero/dev/meta-graph/mgvenv/lib/python3.6/site-packages/torch_sparse/__init__.py", line 2, in <module>
    from .coalesce import coalesce
  File "/home/piero/dev/meta-graph/mgvenv/lib/python3.6/site-packages/torch_sparse/coalesce.py", line 4, in <module>
    from .utils.unique import unique
  File "/home/piero/dev/meta-graph/mgvenv/lib/python3.6/site-packages/torch_sparse/utils/unique.py", line 5, in <module>
    import torch_sparse.unique_cuda
ImportError: /home/piero/dev/meta-graph/mgvenv/lib/python3.6/site-packages/torch_sparse/unique_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by rusty1s** [comment]
Can you show me the installation log of `torch-sparse`? This also might indicate a mismatch of CUDA versions, so you should check this.

**Comment by w4nderlust** [comment]
Unfortunately I doubt it's a CUDA related issue, as I'm trying to run the same code from a Mac laptop without CUDA and get the same error:
```
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from data import load_dataset
  File "/Users/piero/Development/mgraph/mgraph/data.py", line 8, in <module>
    import torch_geometric.transforms as T
  File "/Users/piero/Development/mgraph/mgvenv/lib/python3.7/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/Users/piero/Development/mgraph/mgvenv/lib/python3.7/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/Users/piero/Development/mgraph/mgvenv/lib/python3.7/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/Users/piero/Development/mgraph/mgvenv/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/Users/piero/Development/mgraph/mgvenv/lib/python3.7/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/Users/piero/Development/mgraph/mgvenv/lib/python3.7/site-packages/torch_sparse/__init__.py", line 2, in <module>
    from .coalesce import coalesce
  File "/Users/piero/Development/mgraph/mgvenv/lib/python3.7/site-packages/torch_sparse/coalesce.py", line 2, in <module>
    import torch_scatter
  File "/Users/piero/Development/mgraph/mgvenv/lib/python3.7/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/Users/piero/Development/mgraph/mgvenv/lib/python3.7/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/Users/piero/Development/mgraph/mgvenv/lib/python3.7/site-packages/torch_scatter/utils/ext.py", line 2, in <module>
    import torch_scatter.scatter_cpu
ImportError: dlopen(/Users/piero/Development/mgraph/mgvenv/lib/python3.7/site-packages/torch_scatter/scatter_cpu.cpython-37m-darwin.so, 2): Symbol not found: __ZN6caffe26detail37_typeMetaDataInstance_preallocated_29E
  Referenced from: /Users/piero/Development/mgraph/mgvenv/lib/python3.7/site-packages/torch_scatter/scatter_cpu.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/piero/Development/mgraph/mgvenv/lib/python3.7/site-packages/torch_scatter/scatter_cpu.cpython-37m-darwin.so

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```
If it is helpful, the python version is 3.7.3

Attatching the log for the installation of torch-sparse on MacOS:
[log.txt](https://github.com/rusty1s/pytorch_scatter/files/3512538/log.txt)

**Comment by rusty1s** [comment]
Your installation suggests that it does not recompile the kernels and is using a cached version instead. Please uninstall the packages first before reinstalling them:
```
pip uninstall torch-scatter torch-sparse
```
Run this command multiple times.

**Comment by w4nderlust** [comment]
Did it several time, also using `--no-cache`, and also recreating a new environment. Had no luck unfortunately.

**Comment by rusty1s** [comment]
Which gcc version are you using?

**Comment by w4nderlust** [comment]
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by rusty1s** [comment]
To be honest, I do not really know. macOS installation should run fine following https://github.com/rusty1s/pytorch_geometric/issues/18#issuecomment-464368871. For Ubuntu, your error message sounds CUDA related, as it finds scatter_cpu, but not scatter_cuda.

**Comment by w4nderlust** [comment]
Not using conda unfortunately, both mac and ubuntu.
The version of gcc under ubuntu is 7.4.0 by the way, and cuda is 10.1
Anyway, thank you for your help, much appreciated.

**Comment by lihua213** [comment]
The error can be solved by "import torch" first!
for example:
import torch
from torch_sparse import spspmm

**Comment by q1221sr** [comment]
> > > > import torch
> > > > from torch_scatter import scatter_max
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/home/ahyun/anaconda3/envs/py36torch040/lib/python3.6/site-packages/torch_scatter/**init**.py", line 3, in 
> > > > from .mul import scatter_mul
> > > > File "/home/ahyun/anaconda3/envs/py36torch040/lib/python3.6/site-packages/torch_scatter/mul.py", line 3, in 
> > > > from torch_scatter.utils.ext import get_func
> > > > File "/home/ahyun/anaconda3/envs/py36torch040/lib/python3.6/site-packages/torch_scatter/utils/ext.py", line 2, in 
> > > > import scatter_cpu
> > > > ImportError: /home/ahyun/anaconda3/envs/py36torch040/lib/python3.6/site-packages/scatter_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at6detail20DynamicCUDAInterface10set_deviceE
> 
> I tried install w/ both pytorch v 0.4.0 and 0.4.1, via pip and source and get the same error How do I resolve this issue?

hey, guys
just do it in your conda env!

pip uninstall torch-sparse
pip install torch-sparse==0.6.0

not 0.6.12!
