### ISSUE TITLE
suddenly out of memory, need 259G memory

### ISSUE THREAD

**Issue by yzl96** [rusty1s/pytorch_scatter#84]
sometimes, I have out of memory problem, the reason is scatter_max, I don't konw why, scatter_max looks like not stable.

log:
Traceback (most recent call last):
  File "/media/ovo/file/detection/gg/test.py", line 74, in <module>
    mvf(ip)
  File "/home/ovo/anaconda3/envs/detection/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "./model.py", line 44, in forward
    fv_maxpool, ind = scatter_max(fv_fc_output, fv_mapping_pv, dim=0)
  File "/home/ovo/anaconda3/envs/detection/lib/python3.7/site-packages/torch_scatter/max.py", line 106, in scatter_max
    src, out, index, dim = gen(src, index, dim, out, dim_size, fill_value)
  File "/home/ovo/anaconda3/envs/detection/lib/python3.7/site-packages/torch_scatter/utils/gen.py", line 44, in gen
    out = src.new_full(out_size, fill_value)
RuntimeError: CUDA out of memory. Tried to allocate 259.00 GiB (GPU 0; 5.93 GiB total capacity; 108.37 MiB already allocated; 4.31 GiB free; 15.63 MiB cached)

**Comment by rusty1s** [comment]
Can you run your script with `CUDA_LAUNCH_BLOCKING=1` to see exactly where the error occurs?

**Comment by yzl96** [comment]
sorry to bother you, CUDA_LAUNCH_BLOCKING=1 tells me index is out of range, fix it.
