### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda'

### ISSUE THREAD

**Issue by drashtib** [rusty1s/pytorch_scatter#89]
I am getting this error. 
Environment:
OS: Windows 10
Python version: 3.6
PyTorch version: 1.2.0
CUDA: 10

How did you try to install PyTorch Geometric and its extensions (pip, source): pip

I have tried everything suggested in below link:
https://github.com/rusty1s/pytorch_geometric/issues/633 
but doesn't work anything. Please suggest a solution. 

"""
Traceback (most recent call last):

  File "<ipython-input-1-9ee39f380afa>", line 1, in <module>
    runfile('C:/Users/Drashti Bhatt/Desktop/New folder/challenge.py', wdir='C:/Users/Drashti Bhatt/Desktop/New folder')

  File "C:\Users\Drashti Bhatt\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\Drashti Bhatt\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Drashti Bhatt/Desktop/New folder/challenge.py", line 14, in <module>
    from torch_geometric.data import InMemoryDataset

  File "C:\Users\Drashti Bhatt\Anaconda3\lib\site-packages\torch_geometric\__init__.py", line 2, in <module>
    import torch_geometric.nn

  File "C:\Users\Drashti Bhatt\Anaconda3\lib\site-packages\torch_geometric\nn\__init__.py", line 2, in <module>
    from .data_parallel import DataParallel

  File "C:\Users\Drashti Bhatt\Anaconda3\lib\site-packages\torch_geometric\nn\data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch

  File "C:\Users\Drashti Bhatt\Anaconda3\lib\site-packages\torch_geometric\data\__init__.py", line 1, in <module>
    from .data import Data

  File "C:\Users\Drashti Bhatt\Anaconda3\lib\site-packages\torch_geometric\data\data.py", line 7, in <module>
    from torch_sparse import coalesce

  File "C:\Users\Drashti Bhatt\Anaconda3\lib\site-packages\torch_sparse\__init__.py", line 2, in <module>
    from .coalesce import coalesce

  File "C:\Users\Drashti Bhatt\Anaconda3\lib\site-packages\torch_sparse\coalesce.py", line 2, in <module>
    import torch_scatter

  File "C:\Users\Drashti Bhatt\Anaconda3\lib\site-packages\torch_scatter\__init__.py", line 3, in <module>
    from .mul import scatter_mul

  File "C:\Users\Drashti Bhatt\Anaconda3\lib\site-packages\torch_scatter\mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func

  File "C:\Users\Drashti Bhatt\Anaconda3\lib\site-packages\torch_scatter\utils\ext.py", line 5, in <module>
    import torch_scatter.scatter_cuda

ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda'"""

**Comment by rusty1s** [comment]
Can you show me the installation log when installing a clean version of torch-scatter?

**Comment by drashtib** [comment]
hi. the problem is solved. Thanks:)

**Comment by NathanielNguyen11** [comment]
@drashtib 
Hello, can you tell us about your solution, please!

**Comment by jwzhi** [comment]
Same issue, how this is solved?

**Comment by NathanielNguyen11** [comment]
I solved the problem. It caused by the cuda on Windows:
I installed it separately and eventually It worked well.
