### ISSUE TITLE
can not import pytorch_scatter

### ISSUE THREAD

**Issue by XuandongZhao** [rusty1s/pytorch_scatter#9]
I use mac os, and the version is 10.14. But when I want to use torch_scatter, there is a problem as follows. Do you know how to fix it?

>import torch
from torch_scatter import scatter_max
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zhaoxuandong/anaconda3/lib/python3.6/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/Users/zhaoxuandong/anaconda3/lib/python3.6/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/Users/zhaoxuandong/anaconda3/lib/python3.6/site-packages/torch_scatter/utils/ext.py", line 2, in <module>
    import scatter_cpu
ImportError: dlopen(/Users/zhaoxuandong/anaconda3/lib/python3.6/site-packages/scatter_cpu.cpython-36m-darwin.so, 2): Symbol not found: __ZN2at5ErrorC1ENS_14SourceLocationESs
  Referenced from: /Users/zhaoxuandong/anaconda3/lib/python3.6/site-packages/scatter_cpu.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/zhaoxuandong/anaconda3/lib/python3.6/site-packages/scatter_cpu.cpython-36m-darwin.so

**Comment by rusty1s** [comment]
Related to https://github.com/rusty1s/pytorch_geometric/issues/18
