### ISSUE TITLE
scatter_softmax can not work on gpu

### ISSUE THREAD

**Issue by wjlpku** [rusty1s/pytorch_scatter#93]
Hi, I do not know how to use scatter_softmax on gpu?
Please help me~

torch version: '1.3.1'
torch_scatter.__version__: '1.4.0'

When I write code:
```
    def sparse_softmax(s):
    i = s._indices()
    v = s._values()
    return torch.sparse.FloatTensor(i, scatter_softmax(v, i[0]), s.size())

i = torch.LongTensor([[0, 0, 2],
                      [2, 0, 2]])
v = torch.FloatTensor([1, 1, 1])
A = torch.sparse.FloatTensor(i, v, torch.Size([3,3]))
A = A.cuda()
B = sparse_softmax(A)
```

It works well on CPU if I do not set "A = A.cuda()"
when I set A = A.cuda()

```
Traceback (most recent call last):
  File "gate_old.py", line 68, in <module>
    B = sparse_softmax(A)
  File "gate_old.py", line 54, in sparse_softmax
    return torch.sparse.FloatTensor(i, scatter_softmax(v, i[0]), s.size())
  File "/home/wangjialin/anaconda3/lib/python3.7/site-packages/torch_scatter/composite/softmax.py", line 35, in scatter_softmax
    print(max_value_per_index, index)
  File "/home/wangjialin/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 130, in __repr__
    return torch._tensor_str._str(self)
  File "/home/wangjialin/anaconda3/lib/python3.7/site-packages/torch/_tensor_str.py", line 311, in _str
    tensor_str = _tensor_str(self, indent)
  File "/home/wangjialin/anaconda3/lib/python3.7/site-packages/torch/_tensor_str.py", line 209, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/wangjialin/anaconda3/lib/python3.7/site-packages/torch/_tensor_str.py", line 87, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
  File "/home/wangjialin/anaconda3/lib/python3.7/site-packages/torch/functional.py", line 227, in isfinite
    return (tensor == tensor) & (tensor.abs() != inf)
RuntimeError: CUDA error: invalid dev
```

**Comment by rusty1s** [comment]
It seems like `scatter_softmax` is outputting `inf`. Can you verify if and why this is the case?
